// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCRtpSendParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCRtpSendParameters : public wrapper::org::webRtc::RTCRtpSendParameters
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCRtpSendParameters, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCRtpSendParameters, WrapperImplType);
          RTCRtpSendParametersWeakPtr thisWeak_;

          RTCRtpSendParameters() noexcept;
          virtual ~RTCRtpSendParameters() noexcept;
          void wrapper_init_org_webRtc_RTCRtpSendParameters() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

