// Generated by zsLibEventingTool

#include "impl_org_webRtc_RTCIceCandidate.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCIceCandidate::RTCIceCandidate() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCIceCandidatePtr wrapper::org::webRtc::RTCIceCandidate::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webRtc::RTCIceCandidate>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCIceCandidate::~RTCIceCandidate() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCIceCandidate::wrapper_init_org_webRtc_RTCIceCandidate() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCIceCandidate::wrapper_init_org_webRtc_RTCIceCandidate(wrapper::org::webRtc::RTCIceCandidateInitPtr init) noexcept(false)
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCIceCandidateInitPtr wrapper::impl::org::webRtc::RTCIceCandidate::toJson() noexcept
{
  wrapper::org::webRtc::RTCIceCandidateInitPtr result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceCandidate::get_candidate() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceCandidate::get_sdpMid() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< unsigned short > wrapper::impl::org::webRtc::RTCIceCandidate::get_sdpMLineIndex() noexcept
{
  Optional< unsigned short > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceCandidate::get_foundation() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCIceComponent > wrapper::impl::org::webRtc::RTCIceCandidate::get_component() noexcept
{
  Optional< wrapper::org::webRtc::RTCIceComponent > result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< unsigned long > wrapper::impl::org::webRtc::RTCIceCandidate::get_priority() noexcept
{
  Optional< unsigned long > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceCandidate::get_ip() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCIceProtocol > wrapper::impl::org::webRtc::RTCIceCandidate::get_protocol() noexcept
{
  Optional< wrapper::org::webRtc::RTCIceProtocol > result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< uint16_t > wrapper::impl::org::webRtc::RTCIceCandidate::get_port() noexcept
{
  Optional< uint16_t > result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCIceCandidateType > wrapper::impl::org::webRtc::RTCIceCandidate::get_type() noexcept
{
  Optional< wrapper::org::webRtc::RTCIceCandidateType > result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCIceTcpCandidateType > wrapper::impl::org::webRtc::RTCIceCandidate::get_tcpType() noexcept
{
  Optional< wrapper::org::webRtc::RTCIceTcpCandidateType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceCandidate::get_relatedAddress() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< uint16_t > wrapper::impl::org::webRtc::RTCIceCandidate::get_relatedPort() noexcept
{
  Optional< uint16_t > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceCandidate::get_usernameFragment() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCIceCandidate::set_usernameFragment(String value) noexcept
{
}


