// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCDtlsFingerprint.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCDtlsFingerprint : public wrapper::org::webRtc::RTCDtlsFingerprint
        {
          RTCDtlsFingerprintWeakPtr thisWeak_;

          RTCDtlsFingerprint() noexcept;
          virtual ~RTCDtlsFingerprint() noexcept;

          // methods RTCDtlsFingerprint
          void wrapper_init_org_webRtc_RTCDtlsFingerprint() noexcept override;
          void wrapper_init_org_webRtc_RTCDtlsFingerprint(wrapper::org::webRtc::RTCDtlsFingerprintPtr source) noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

