// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCRtpHeaderExtensionParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCRtpHeaderExtensionParameters : public wrapper::org::webRtc::RTCRtpHeaderExtensionParameters
        {
          RTCRtpHeaderExtensionParametersWeakPtr thisWeak_;

          RTCRtpHeaderExtensionParameters() noexcept;
          virtual ~RTCRtpHeaderExtensionParameters() noexcept;
          void wrapper_init_org_webRtc_RTCRtpHeaderExtensionParameters() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

