// Generated by zsLibEventingTool

#include "impl_org_webrtc_RTCOutboundRtpStreamStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::RTCOutboundRtpStreamStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCOutboundRtpStreamStatsPtr wrapper::org::webrtc::RTCOutboundRtpStreamStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::~RTCOutboundRtpStreamStats()
{
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webrtc::RTCStatsType > wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_statsType() noexcept
{
  Optional< wrapper::org::webrtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_id() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< uint32_t > wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_ssrc() noexcept
{
  Optional< uint32_t > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_associatedStatId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_isRemote() noexcept
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_mediaType() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_mediaTrackId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_transportId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_codecId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_firCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_pliCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_nackCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_sliCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::wrapper_init_org_webrtc_RTCOutboundRtpStreamStats() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::wrapper_init_org_webrtc_RTCOutboundRtpStreamStats(wrapper::org::webrtc::RTCOutboundRtpStreamStatsPtr source) noexcept
{
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_packetsSent() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long long wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_bytesSent() noexcept
{
  unsigned long long result {};
  return result;
}

//------------------------------------------------------------------------------
double wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_targetBitrate() noexcept
{
  double result {};
  return result;
}

//------------------------------------------------------------------------------
double wrapper::impl::org::webrtc::RTCOutboundRtpStreamStats::get_roundTripTime() noexcept
{
  double result {};
  return result;
}


