// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCRtpCapabilities.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCRtpCapabilities : public wrapper::org::webRtc::RTCRtpCapabilities
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCRtpCapabilities, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCRtpCapabilities, WrapperImplType);
          RTCRtpCapabilitiesWeakPtr thisWeak_;

          RTCRtpCapabilities() noexcept;
          virtual ~RTCRtpCapabilities() noexcept;
          void wrapper_init_org_webRtc_RTCRtpCapabilities() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

