// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCRtpSynchronizationSource.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCRtpSynchronizationSource : public wrapper::org::webRtc::RTCRtpSynchronizationSource
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCRtpSynchronizationSource, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCRtpSynchronizationSource, WrapperImplType);
          RTCRtpSynchronizationSourceWeakPtr thisWeak_;

          RTCRtpSynchronizationSource() noexcept;
          virtual ~RTCRtpSynchronizationSource() noexcept;
          void wrapper_init_org_webRtc_RTCRtpSynchronizationSource() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

