// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_VideoTrackSource.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct VideoTrackSource : public wrapper::org::webrtc::VideoTrackSource
        {
          VideoTrackSourceWeakPtr thisWeak_;

          VideoTrackSource() noexcept;
          virtual ~VideoTrackSource() noexcept;

          // properties MediaTrackSource
          wrapper::org::webrtc::MediaSourceState get_state() noexcept override;
          bool get_remote() noexcept override;
          void wrapper_init_org_webrtc_VideoTrackSource() noexcept override;

          // properties VideoTrackSource
          bool get_isScreencast() noexcept override;
          void set_isScreencast(bool value) noexcept override;
          Optional< bool > get_needsDenoising() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

