// Generated by zsLibEventingTool

#include "impl_org_webRtc_RTCDataChannel.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCDataChannel::RTCDataChannel() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCDataChannelPtr wrapper::org::webRtc::RTCDataChannel::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webRtc::RTCDataChannel>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCDataChannel::~RTCDataChannel() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCDataChannel::wrapper_init_org_webRtc_RTCDataChannel() noexcept
{
}

//------------------------------------------------------------------------------
shared_ptr< PromiseWithHolderPtr< wrapper::org::webRtc::RTCStatsReportPtr > > wrapper::impl::org::webRtc::RTCDataChannel::getStats(wrapper::org::webRtc::RTCStatsTypeSetPtr statTypes) noexcept(false)
{
  shared_ptr< PromiseWithHolderPtr< wrapper::org::webRtc::RTCStatsReportPtr > > result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCDataChannel::close() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCDataChannel::send(String text) noexcept(false)
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCDataChannel::send(SecureByteBlockPtr data) noexcept(false)
{
}

//------------------------------------------------------------------------------
unsigned short wrapper::impl::org::webRtc::RTCDataChannel::get_id() noexcept
{
  unsigned short result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCDataChannel::get_label() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::webRtc::RTCDataChannel::get_ordered() noexcept
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
::zsLib::Milliseconds wrapper::impl::org::webRtc::RTCDataChannel::get_maxPacketLifeTime() noexcept
{
  ::zsLib::Milliseconds result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned short wrapper::impl::org::webRtc::RTCDataChannel::get_maxRetransmits() noexcept
{
  unsigned short result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCDataChannel::get_protocol() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::webRtc::RTCDataChannel::get_negotiated() noexcept
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCPriorityType wrapper::impl::org::webRtc::RTCDataChannel::get_priority() noexcept
{
  wrapper::org::webRtc::RTCPriorityType result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCDataChannelState wrapper::impl::org::webRtc::RTCDataChannel::get_readyState() noexcept
{
  wrapper::org::webRtc::RTCDataChannelState result {};
  return result;
}

//------------------------------------------------------------------------------
uint64_t wrapper::impl::org::webRtc::RTCDataChannel::get_bufferedAmount() noexcept
{
  uint64_t result {};
  return result;
}

//------------------------------------------------------------------------------
uint64_t wrapper::impl::org::webRtc::RTCDataChannel::get_bufferedAmountLowThreshold() noexcept
{
  uint64_t result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCDataChannel::set_bufferedAmountLowThreshold(uint64_t value) noexcept
{
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCDataChannel::get_binaryType() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCDataChannel::set_binaryType(String value) noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCDataChannel::wrapper_onObserverCountChanged(size_t count) noexcept
{
}


