// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCCodecStats.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCCodecStats : public wrapper::org::webRtc::RTCCodecStats
        {
          RTCCodecStatsWeakPtr thisWeak_;

          RTCCodecStats() noexcept;
          virtual ~RTCCodecStats() noexcept;

          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webRtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // properties RTCCodecStats
          Optional< uint8_t > get_payloadType() noexcept override;
          Optional< wrapper::org::webRtc::RTCCodecType> get_codecType() noexcept override;
          String get_transportId() noexcept override;
          void set_transportId(String value) noexcept override;
          String get_mimeType() noexcept override;
          unsigned long get_clockRate() noexcept override;
          Optional< unsigned long > get_channels() noexcept override;
          String get_sdpFmtpLine() noexcept override;
          String get_implementation() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

