// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_MediaSource.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct MediaSource : public wrapper::org::webrtc::MediaSource
        {
          MediaSourceWeakPtr thisWeak_;

          MediaSource() noexcept;
          virtual ~MediaSource() noexcept;
          void wrapper_init_org_webrtc_MediaSource() noexcept override;

          // properties MediaSource
          AnyPtr get_source() noexcept override;
          void set_source(AnyPtr value) noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

