// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCTrackEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCTrackEvent : public wrapper::org::webrtc::RTCTrackEvent
        {
          RTCTrackEventWeakPtr thisWeak_;

          RTCTrackEvent() noexcept;
          virtual ~RTCTrackEvent() noexcept;
          void wrapper_init_org_webrtc_RTCTrackEvent() noexcept override;

          // properties RTCTrackEvent
          wrapper::org::webrtc::RTCRtpReceiverPtr get_receiver() noexcept override;
          wrapper::org::webrtc::MediaStreamTrackPtr get_track() noexcept override;
          wrapper::org::webrtc::RTCRtpTransceiverPtr get_transceiver() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

