// Generated by zsLibEventingTool

#include "impl_org_webRtc_RTCCodecStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCCodecStats::RTCCodecStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCCodecStatsPtr wrapper::org::webRtc::RTCCodecStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webRtc::RTCCodecStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCCodecStats::~RTCCodecStats() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webRtc::RTCCodecStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCStatsType > wrapper::impl::org::webRtc::RTCCodecStats::get_statsType() noexcept
{
  Optional< wrapper::org::webRtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCodecStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCodecStats::get_id() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< uint8_t > wrapper::impl::org::webRtc::RTCCodecStats::get_payloadType() noexcept
{
  Optional< uint8_t > result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCCodecType> wrapper::impl::org::webRtc::RTCCodecStats::get_codecType() noexcept
{
  wrapper::org::webRtc::RTCCodecType result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCodecStats::get_transportId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCCodecStats::set_transportId(String value) noexcept
{
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCodecStats::get_mimeType() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webRtc::RTCCodecStats::get_clockRate() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< unsigned long > wrapper::impl::org::webRtc::RTCCodecStats::get_channels() noexcept
{
  Optional< unsigned long > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCodecStats::get_sdpFmtpLine() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCodecStats::get_implementation() noexcept
{
  String result {};
  return result;
}


