// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCOAuthCredential.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCOAuthCredential : public wrapper::org::webrtc::RTCOAuthCredential
        {
          RTCOAuthCredentialWeakPtr thisWeak_;

          RTCOAuthCredential() noexcept;
          virtual ~RTCOAuthCredential() noexcept;

          // methods RTCOAuthCredential
          void wrapper_init_org_webrtc_RTCOAuthCredential() noexcept override;
          void wrapper_init_org_webrtc_RTCOAuthCredential(wrapper::org::webrtc::RTCOAuthCredentialPtr source) noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

