// Generated by zsLibEventingTool

#include "impl_org_webrtc_RTCRtpTransceiver.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCRtpTransceiver::RTCRtpTransceiver() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCRtpTransceiverPtr wrapper::org::webrtc::RTCRtpTransceiver::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::RTCRtpTransceiver>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCRtpTransceiver::~RTCRtpTransceiver()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCRtpTransceiver::stop() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCRtpTransceiver::setCodecPreferences(shared_ptr< list< wrapper::org::webrtc::RTCRtpCodecCapabilityPtr > > codecs) noexcept(false)
{
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCRtpTransceiver::get_mid() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCRtpSenderPtr wrapper::impl::org::webrtc::RTCRtpTransceiver::get_sender() noexcept
{
  wrapper::org::webrtc::RTCRtpSenderPtr result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCRtpReceiverPtr wrapper::impl::org::webrtc::RTCRtpTransceiver::get_receiver() noexcept
{
  wrapper::org::webrtc::RTCRtpReceiverPtr result {};
  return result;
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::webrtc::RTCRtpTransceiver::get_stopped() noexcept
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCRtpTransceiverDirection wrapper::impl::org::webrtc::RTCRtpTransceiver::get_direction() noexcept
{
  wrapper::org::webrtc::RTCRtpTransceiverDirection result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCRtpTransceiver::set_direction(wrapper::org::webrtc::RTCRtpTransceiverDirection value) noexcept
{
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webrtc::RTCRtpTransceiverDirection > wrapper::impl::org::webrtc::RTCRtpTransceiver::get_currentDirection() noexcept
{
  Optional< wrapper::org::webrtc::RTCRtpTransceiverDirection > result {};
  return result;
}


