// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCSrtpTransportStats.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCSrtpTransportStats : public wrapper::org::webrtc::RTCSrtpTransportStats
        {
          RTCSrtpTransportStatsWeakPtr thisWeak_;

          RTCSrtpTransportStats() noexcept;
          virtual ~RTCSrtpTransportStats() noexcept;

          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webrtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // methods RTCSrtpTransportStats
          void wrapper_init_org_webrtc_RTCSrtpTransportStats() noexcept override;
          void wrapper_init_org_webrtc_RTCSrtpTransportStats(wrapper::org::webrtc::RTCSrtpTransportStatsPtr source) noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

