// Generated by zsLibEventingTool

#include "impl_org_webrtc_EventQueue.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::EventQueue::EventQueue() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::EventQueuePtr wrapper::org::webrtc::EventQueue::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::EventQueue>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::EventQueue::~EventQueue()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::EventQueue::wrapper_init_org_webrtc_EventQueue(AnyPtr queue) noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::EventQueuePtr wrapper::org::webrtc::EventQueue::getDefaultForUi() noexcept
{
  wrapper::org::webrtc::EventQueuePtr result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::EventQueuePtr wrapper::org::webrtc::EventQueue::get_singleton() noexcept
{
  wrapper::org::webrtc::EventQueuePtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::org::webrtc::EventQueue::set_singleton(wrapper::org::webrtc::EventQueuePtr value) noexcept
{
}

//------------------------------------------------------------------------------
AnyPtr wrapper::impl::org::webrtc::EventQueue::get_queue() noexcept
{
  AnyPtr result {};
  return result;
}


