// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCPeerConnectionIceErrorEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCPeerConnectionIceErrorEvent : public wrapper::org::webrtc::RTCPeerConnectionIceErrorEvent
        {
          RTCPeerConnectionIceErrorEventWeakPtr thisWeak_;

          RTCPeerConnectionIceErrorEvent() noexcept;
          virtual ~RTCPeerConnectionIceErrorEvent() noexcept;
          void wrapper_init_org_webrtc_RTCPeerConnectionIceErrorEvent() noexcept override;

          // properties RTCPeerConnectionIceErrorEvent
          String get_hostCandidate() noexcept override;
          String get_url() noexcept override;
          unsigned short get_errorCode() noexcept override;
          String get_errorText() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

