// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCIceGathererStats.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCIceGathererStats : public wrapper::org::webrtc::RTCIceGathererStats
        {
          RTCIceGathererStatsWeakPtr thisWeak_;

          RTCIceGathererStats() noexcept;
          virtual ~RTCIceGathererStats() noexcept;

          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webrtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // methods RTCIceGathererStats
          void wrapper_init_org_webrtc_RTCIceGathererStats() noexcept override;
          void wrapper_init_org_webrtc_RTCIceGathererStats(wrapper::org::webrtc::RTCIceGathererStatsPtr source) noexcept override;

          // properties RTCIceGathererStats
          unsigned long long get_bytesSent() noexcept override;
          unsigned long long get_bytesReceived() noexcept override;
          String get_rtcpGathererStatsId() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

