// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCStatsReport.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCStatsReport : public wrapper::org::webrtc::RTCStatsReport
        {
          RTCStatsReportWeakPtr thisWeak_;

          RTCStatsReport() noexcept;
          virtual ~RTCStatsReport() noexcept;

          // methods RTCStatsReport
          wrapper::org::webrtc::RTCStatsPtr getStats(String id) noexcept override;

          // properties RTCStatsReport
          uint64_t get_objectId() noexcept override;
          shared_ptr< list< String > > get_statsIds() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

