// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCRtpContributingSource.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCRtpContributingSource : public wrapper::org::webrtc::RTCRtpContributingSource
        {
          RTCRtpContributingSourceWeakPtr thisWeak_;

          RTCRtpContributingSource() noexcept;
          virtual ~RTCRtpContributingSource() noexcept;
          void wrapper_init_org_webrtc_RTCRtpContributingSource() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

