// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCDtlsTransportStats.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCDtlsTransportStats : public wrapper::org::webrtc::RTCDtlsTransportStats
        {
          RTCDtlsTransportStatsWeakPtr thisWeak_;

          RTCDtlsTransportStats() noexcept;
          virtual ~RTCDtlsTransportStats() noexcept;

          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webrtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // methods RTCDtlsTransportStats
          void wrapper_init_org_webrtc_RTCDtlsTransportStats() noexcept override;
          void wrapper_init_org_webrtc_RTCDtlsTransportStats(wrapper::org::webrtc::RTCDtlsTransportStatsPtr source) noexcept override;

          // properties RTCDtlsTransportStats
          String get_localCertificateId() noexcept override;
          String get_remoteCertificateId() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

