// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCRtpEncodingParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCRtpEncodingParameters : public wrapper::org::webRtc::RTCRtpEncodingParameters
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCRtpEncodingParameters, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCRtpEncodingParameters, WrapperImplType);
          RTCRtpEncodingParametersWeakPtr thisWeak_;

          RTCRtpEncodingParameters() noexcept;
          virtual ~RTCRtpEncodingParameters() noexcept;
          void wrapper_init_org_webRtc_RTCRtpEncodingParameters() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

