// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCRSAParams.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCRSAParams : public wrapper::org::webrtc::RTCRSAParams
        {
          RTCRSAParamsWeakPtr thisWeak_;

          RTCRSAParams() noexcept;
          virtual ~RTCRSAParams() noexcept;
          void wrapper_init_org_webrtc_RTCRSAParams() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

