// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCPeerConnectionIceErrorEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCPeerConnectionIceErrorEvent : public wrapper::org::webRtc::RTCPeerConnectionIceErrorEvent
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCPeerConnectionIceErrorEvent, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCPeerConnectionIceErrorEvent, WrapperImplType);
          RTCPeerConnectionIceErrorEventWeakPtr thisWeak_;

          RTCPeerConnectionIceErrorEvent() noexcept;
          virtual ~RTCPeerConnectionIceErrorEvent() noexcept;

          // properties RTCPeerConnectionIceErrorEvent
          String get_hostCandidate() noexcept override;
          String get_url() noexcept override;
          unsigned short get_errorCode() noexcept override;
          String get_errorText() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

