// Generated by zsLibEventingTool

#include "impl_org_webrtc_RTCAnswerOptions.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCAnswerOptions::RTCAnswerOptions() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCAnswerOptionsPtr wrapper::org::webrtc::RTCAnswerOptions::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::RTCAnswerOptions>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCAnswerOptions::~RTCAnswerOptions()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCAnswerOptions::wrapper_init_org_webrtc_RTCAnswerOptions() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCAnswerOptions::wrapper_init_org_webrtc_RTCAnswerOptions(wrapper::org::webrtc::RTCAnswerOptionsPtr source) noexcept
{
}


