// Generated by zsLibEventingTool

#include "impl_org_webrtc_RTCPeerConnectionIceEvent.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCPeerConnectionIceEvent::RTCPeerConnectionIceEvent() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCPeerConnectionIceEventPtr wrapper::org::webrtc::RTCPeerConnectionIceEvent::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::RTCPeerConnectionIceEvent>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCPeerConnectionIceEvent::~RTCPeerConnectionIceEvent()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCPeerConnectionIceEvent::wrapper_init_org_webrtc_RTCPeerConnectionIceEvent() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCIceCandidatePtr wrapper::impl::org::webrtc::RTCPeerConnectionIceEvent::get_candidate() noexcept
{
  wrapper::org::webrtc::RTCIceCandidatePtr result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCPeerConnectionIceEvent::get_url() noexcept
{
  String result {};
  return result;
}


