// Generated by zsLibEventingTool

#include "impl_org_webrtc_RTCMediaStreamStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCMediaStreamStats::RTCMediaStreamStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCMediaStreamStatsPtr wrapper::org::webrtc::RTCMediaStreamStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::RTCMediaStreamStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCMediaStreamStats::~RTCMediaStreamStats() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webrtc::RTCMediaStreamStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webrtc::RTCStatsType > wrapper::impl::org::webrtc::RTCMediaStreamStats::get_statsType() noexcept
{
  Optional< wrapper::org::webrtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCMediaStreamStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCMediaStreamStats::get_id() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCMediaStreamStats::wrapper_init_org_webrtc_RTCMediaStreamStats() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCMediaStreamStats::wrapper_init_org_webrtc_RTCMediaStreamStats(wrapper::org::webrtc::RTCMediaStreamStatsPtr source) noexcept
{
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCMediaStreamStats::get_streamId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
shared_ptr< list< String > > wrapper::impl::org::webrtc::RTCMediaStreamStats::get_trackIds() noexcept
{
  shared_ptr< list< String > > result {};
  return result;
}


