// Generated by zsLibEventingTool

#include "impl_org_webrtc_RTCInboundRtpStreamStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::RTCInboundRtpStreamStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCInboundRtpStreamStatsPtr wrapper::org::webrtc::RTCInboundRtpStreamStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::RTCInboundRtpStreamStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::~RTCInboundRtpStreamStats()
{
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webrtc::RTCStatsType > wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_statsType() noexcept
{
  Optional< wrapper::org::webrtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_id() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< uint32_t > wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_ssrc() noexcept
{
  Optional< uint32_t > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_associatedStatId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_isRemote() noexcept
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_mediaType() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_mediaTrackId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_transportId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_codecId() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_firCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_pliCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_nackCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_sliCount() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::wrapper_init_org_webrtc_RTCInboundRtpStreamStats() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::wrapper_init_org_webrtc_RTCInboundRtpStreamStats(wrapper::org::webrtc::RTCInboundRtpStreamStatsPtr source) noexcept
{
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_packetsReceived() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long long wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_bytesReceived() noexcept
{
  unsigned long long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_packetsLost() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
double wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_jitter() noexcept
{
  double result {};
  return result;
}

//------------------------------------------------------------------------------
double wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_fractionLost() noexcept
{
  double result {};
  return result;
}

//------------------------------------------------------------------------------
::zsLib::Milliseconds wrapper::impl::org::webrtc::RTCInboundRtpStreamStats::get_endToEndDelay() noexcept
{
  ::zsLib::Milliseconds result {};
  return result;
}


