// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCRtpReceiver.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCRtpReceiver : public wrapper::org::webRtc::RTCRtpReceiver
        {
          RTCRtpReceiverWeakPtr thisWeak_;

          RTCRtpReceiver() noexcept;
          virtual ~RTCRtpReceiver() noexcept;

          // methods RTCRtpReceiver
          wrapper::org::webRtc::RTCRtpReceiveParametersPtr getParameters() noexcept override;
          shared_ptr< list< wrapper::org::webRtc::RTCRtpContributingSourcePtr > > getContributingSources() noexcept override;
          shared_ptr< list< wrapper::org::webRtc::RTCRtpSynchronizationSourcePtr > > getSynchronizationSources() noexcept override;

          // properties RTCRtpReceiver
          wrapper::org::webRtc::MediaStreamTrackPtr get_track() noexcept override;
          void set_track(wrapper::org::webRtc::MediaStreamTrackPtr value) noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

