// Generated by zsLibEventingTool

#include "impl_org_webrtc_MediaSource.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::MediaSource::MediaSource() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::MediaSourcePtr wrapper::org::webrtc::MediaSource::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::MediaSource>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::MediaSource::~MediaSource()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::MediaSource::wrapper_init_org_webrtc_MediaSource() noexcept
{
}

//------------------------------------------------------------------------------
AnyPtr wrapper::impl::org::webrtc::MediaSource::get_source() noexcept
{
  AnyPtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::MediaSource::set_source(AnyPtr value) noexcept
{
}


