// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCPeerConnectionStats.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCPeerConnectionStats : public wrapper::org::webRtc::RTCPeerConnectionStats
        {
          RTCPeerConnectionStatsWeakPtr thisWeak_;

          RTCPeerConnectionStats() noexcept;
          virtual ~RTCPeerConnectionStats() noexcept;

          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webRtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // properties RTCPeerConnectionStats
          unsigned long get_dataChannelsOpened() noexcept override;
          unsigned long get_dataChannelsClosed() noexcept override;
          unsigned long get_dataChannelsRequested() noexcept override;
          unsigned long get_dataChannelsAccepted() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

