// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCSessionDescription.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCSessionDescription : public wrapper::org::webrtc::RTCSessionDescription
        {
          RTCSessionDescriptionWeakPtr thisWeak_;

          RTCSessionDescription() noexcept;
          virtual ~RTCSessionDescription() noexcept;

          // methods RTCSessionDescription
          void wrapper_init_org_webrtc_RTCSessionDescription(wrapper::org::webrtc::RTCSessionDescriptionInitPtr init) noexcept(false) override; // throws wrapper::org::webrtc::RTCErrorPtr

          // properties RTCSessionDescription
          wrapper::org::webrtc::RTCSdpType get_sdpType() noexcept override;
          String get_sdp() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

