// Generated by zsLibEventingTool

#include "impl_org_webrtc_RTCStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCStats::RTCStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webrtc::RTCStatsPtr wrapper::org::webrtc::RTCStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webrtc::RTCStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webrtc::RTCStats::~RTCStats() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCStats::wrapper_init_org_webrtc_RTCStats() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webrtc::RTCStats::wrapper_init_org_webrtc_RTCStats(wrapper::org::webrtc::RTCStatsPtr source) noexcept
{
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webrtc::RTCStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webrtc::RTCStatsType > wrapper::impl::org::webrtc::RTCStats::get_statsType() noexcept
{
  Optional< wrapper::org::webrtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webrtc::RTCStats::get_id() noexcept
{
  String result {};
  return result;
}


