// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCCodec.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCCodec : public wrapper::org::webrtc::RTCCodec
        {
          RTCCodecWeakPtr thisWeak_;

          RTCCodec() noexcept;
          virtual ~RTCCodec() noexcept;

          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webrtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // methods RTCCodec
          void wrapper_init_org_webrtc_RTCCodec() noexcept override;
          void wrapper_init_org_webrtc_RTCCodec(wrapper::org::webrtc::RTCCodecPtr source) noexcept override;

          // properties RTCCodec
          Optional< uint8_t > get_payloadType() noexcept override;
          String get_codec() noexcept override;
          unsigned long get_clockRate() noexcept override;
          Optional< unsigned long > get_channels() noexcept override;
          String get_parameters() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

