// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCDtlsFingerprint.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCDtlsFingerprint : public wrapper::org::webrtc::RTCDtlsFingerprint
        {
          RTCDtlsFingerprintWeakPtr thisWeak_;

          RTCDtlsFingerprint() noexcept;
          virtual ~RTCDtlsFingerprint() noexcept;

          // methods RTCDtlsFingerprint
          void wrapper_init_org_webrtc_RTCDtlsFingerprint() noexcept override;
          void wrapper_init_org_webrtc_RTCDtlsFingerprint(wrapper::org::webrtc::RTCDtlsFingerprintPtr source) noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

