// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCError.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCError : public wrapper::org::webrtc::RTCError
        {
          RTCErrorWeakPtr thisWeak_;

          RTCError() noexcept;
          virtual ~RTCError() noexcept;
          void wrapper_init_org_webrtc_RTCError() noexcept override;

          // properties RTCError
          wrapper::org::webrtc::RTCErrorType get_type() noexcept override;
          String get_message() noexcept override;
          bool get_ok() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

