// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_MediaTrackSource.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct MediaTrackSource : public wrapper::org::webrtc::MediaTrackSource
        {
          MediaTrackSourceWeakPtr thisWeak_;

          MediaTrackSource() noexcept;
          virtual ~MediaTrackSource() noexcept;
          void wrapper_init_org_webrtc_MediaTrackSource() noexcept override;

          // properties MediaTrackSource
          wrapper::org::webrtc::MediaSourceState get_state() noexcept override;
          bool get_remote() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

