// Generated by zsLibEventingTool

#include "impl_org_webRtc_RTCCertificateStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCCertificateStats::RTCCertificateStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCCertificateStatsPtr wrapper::org::webRtc::RTCCertificateStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webRtc::RTCCertificateStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCCertificateStats::~RTCCertificateStats() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webRtc::RTCCertificateStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCStatsType > wrapper::impl::org::webRtc::RTCCertificateStats::get_statsType() noexcept
{
  Optional< wrapper::org::webRtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCertificateStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCertificateStats::get_id() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCCertificateStats::wrapper_init_org_webRtc_RTCCertificateStats() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCCertificateStats::wrapper_init_org_webRtc_RTCCertificateStats(wrapper::org::webRtc::RTCCertificateStatsPtr source) noexcept
{
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCertificateStats::get_fingerprint() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCertificateStats::get_fingerprintAlgorithm() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCertificateStats::get_base64Certificate() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCCertificateStats::get_issuerCertificateId() noexcept
{
  String result {};
  return result;
}


