// Generated by zsLibEventingTool

#include "impl_org_webRtc_RTCIceGathererStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCIceGathererStats::RTCIceGathererStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCIceGathererStatsPtr wrapper::org::webRtc::RTCIceGathererStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webRtc::RTCIceGathererStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCIceGathererStats::~RTCIceGathererStats() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webRtc::RTCIceGathererStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCStatsType > wrapper::impl::org::webRtc::RTCIceGathererStats::get_statsType() noexcept
{
  Optional< wrapper::org::webRtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceGathererStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceGathererStats::get_id() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCIceGathererStats::wrapper_init_org_webRtc_RTCIceGathererStats() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCIceGathererStats::wrapper_init_org_webRtc_RTCIceGathererStats(wrapper::org::webRtc::RTCIceGathererStatsPtr source) noexcept
{
}

//------------------------------------------------------------------------------
unsigned long long wrapper::impl::org::webRtc::RTCIceGathererStats::get_bytesSent() noexcept
{
  unsigned long long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long long wrapper::impl::org::webRtc::RTCIceGathererStats::get_bytesReceived() noexcept
{
  unsigned long long result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCIceGathererStats::get_rtcpGathererStatsId() noexcept
{
  String result {};
  return result;
}


