// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_Constraint.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct Constraint : public wrapper::org::webrtc::Constraint
        {
          ConstraintWeakPtr thisWeak_;

          Constraint() noexcept;
          virtual ~Constraint() noexcept;

          // methods Constraint
          void wrapper_init_org_webrtc_Constraint() noexcept override;
          void wrapper_init_org_webrtc_Constraint(wrapper::org::webrtc::ConstraintPtr source) noexcept override;
          void wrapper_init_org_webrtc_Constraint(
            String key,
            String value
            ) noexcept override;

          // properties Constraint
          String get_key() noexcept override;
          void set_key(String value) noexcept override;
          String get_value() noexcept override;
          void set_value(String value) noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

