// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCRtpRtxParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCRtpRtxParameters : public wrapper::org::webRtc::RTCRtpRtxParameters
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCRtpRtxParameters, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCRtpRtxParameters, WrapperImplType);
          RTCRtpRtxParametersWeakPtr thisWeak_;

          RTCRtpRtxParameters() noexcept;
          virtual ~RTCRtpRtxParameters() noexcept;
          void wrapper_init_org_webRtc_RTCRtpRtxParameters() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

