// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCStatsReport.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCStatsReport : public wrapper::org::webRtc::RTCStatsReport
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCStatsReport, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCStatsReport, WrapperImplType);
          RTCStatsReportWeakPtr thisWeak_;

          RTCStatsReport() noexcept;
          virtual ~RTCStatsReport() noexcept;

          // methods RTCStatsReport
          wrapper::org::webRtc::RTCStatsPtr getStats(String id) noexcept override;

          // properties RTCStatsReport
          uint64_t get_objectId() noexcept override;
          shared_ptr< list< String > > get_statsIds() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

