// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCRtpCapabilities.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCRtpCapabilities : public wrapper::org::webrtc::RTCRtpCapabilities
        {
          RTCRtpCapabilitiesWeakPtr thisWeak_;

          RTCRtpCapabilities() noexcept;
          virtual ~RTCRtpCapabilities() noexcept;
          void wrapper_init_org_webrtc_RTCRtpCapabilities() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

