// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_VideoCapturerInputSize.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct VideoCapturerInputSize : public wrapper::org::webRtc::VideoCapturerInputSize
        {
          VideoCapturerInputSizeWeakPtr thisWeak_;

          VideoCapturerInputSize() noexcept;
          virtual ~VideoCapturerInputSize() noexcept;
          void wrapper_init_org_webRtc_VideoCapturerInputSize() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

