// Generated by zsLibEventingTool

#include "impl_org_webRtc_RTCSctpTransportStats.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCSctpTransportStats::RTCSctpTransportStats() noexcept
{
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::RTCSctpTransportStatsPtr wrapper::org::webRtc::RTCSctpTransportStats::wrapper_create() noexcept
{
  auto pThis = make_shared<wrapper::impl::org::webRtc::RTCSctpTransportStats>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::webRtc::RTCSctpTransportStats::~RTCSctpTransportStats() noexcept
{
  thisWeak_.reset();
}

//------------------------------------------------------------------------------
::zsLib::Time wrapper::impl::org::webRtc::RTCSctpTransportStats::get_timestamp() noexcept
{
  ::zsLib::Time result {};
  return result;
}

//------------------------------------------------------------------------------
Optional< wrapper::org::webRtc::RTCStatsType > wrapper::impl::org::webRtc::RTCSctpTransportStats::get_statsType() noexcept
{
  Optional< wrapper::org::webRtc::RTCStatsType > result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCSctpTransportStats::get_statsTypeOther() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::webRtc::RTCSctpTransportStats::get_id() noexcept
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCSctpTransportStats::wrapper_init_org_webRtc_RTCSctpTransportStats() noexcept
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::webRtc::RTCSctpTransportStats::wrapper_init_org_webRtc_RTCSctpTransportStats(wrapper::org::webRtc::RTCSctpTransportStatsPtr source) noexcept
{
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webRtc::RTCSctpTransportStats::get_dataChannelsOpened() noexcept
{
  unsigned long result {};
  return result;
}

//------------------------------------------------------------------------------
unsigned long wrapper::impl::org::webRtc::RTCSctpTransportStats::get_dataChannelsClosed() noexcept
{
  unsigned long result {};
  return result;
}


