// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webRtc_RTCVideoReceiverStats.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webRtc {

        struct RTCVideoReceiverStats : public wrapper::org::webRtc::RTCVideoReceiverStats
        {
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::webRtc::RTCVideoReceiverStats, WrapperType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::impl::org::webRtc::RTCVideoReceiverStats, WrapperImplType);
          RTCVideoReceiverStatsWeakPtr thisWeak_;

          RTCVideoReceiverStats() noexcept;
          virtual ~RTCVideoReceiverStats() noexcept;


          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webRtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // properties RTCMediaHandlerStats
          String get_trackIdentifier() noexcept override;
          Optional< bool > get_remoteSource() noexcept override;
          bool get_ended() noexcept override;
          String get_kind() noexcept override;
          wrapper::org::webRtc::RTCPriorityType get_priority() noexcept override;

          // properties RTCVideoHandlerStats
          unsigned long get_frameWidth() noexcept override;
          unsigned long get_frameHeight() noexcept override;
          double get_framesPerSecond() noexcept override;

          // properties RTCVideoReceiverStats
          ::zsLib::Time get_estimatedPlayoutTimestamp() noexcept override;
          ::zsLib::Milliseconds get_jitterBufferDelay() noexcept override;
          unsigned long long get_jitterBufferEmittedCount() noexcept override;
          unsigned long get_framesReceived() noexcept override;
          unsigned long get_keyFramesReceived() noexcept override;
          unsigned long get_framesDecoded() noexcept override;
          unsigned long get_framesDropped() noexcept override;
          unsigned long get_partialFramesLost() noexcept override;
          unsigned long get_fullFramesLost() noexcept override;
        };

      } // webRtc
    } // org
  } // namespace impl
} // namespace wrapper

