// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_webrtc_RTCCertificateStats.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace webrtc {

        struct RTCCertificateStats : public wrapper::org::webrtc::RTCCertificateStats
        {
          RTCCertificateStatsWeakPtr thisWeak_;

          RTCCertificateStats() noexcept;
          virtual ~RTCCertificateStats() noexcept;

          // properties RTCStats
          ::zsLib::Time get_timestamp() noexcept override;
          Optional< wrapper::org::webrtc::RTCStatsType > get_statsType() noexcept override;
          String get_statsTypeOther() noexcept override;
          String get_id() noexcept override;

          // methods RTCCertificateStats
          void wrapper_init_org_webrtc_RTCCertificateStats() noexcept override;
          void wrapper_init_org_webrtc_RTCCertificateStats(wrapper::org::webrtc::RTCCertificateStatsPtr source) noexcept override;

          // properties RTCCertificateStats
          String get_fingerprint() noexcept override;
          String get_fingerprintAlgorithm() noexcept override;
          String get_base64Certificate() noexcept override;
          String get_issuerCertificateId() noexcept override;
        };

      } // webrtc
    } // org
  } // namespace impl
} // namespace wrapper

