// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpFlexFecCodecParameterSettings.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpFlexFecCodecParameterSettings : public wrapper::org::ortc::RTCRtpFlexFecCodecParameterSettings
        {
          RTCRtpFlexFecCodecParameterSettingsWeakPtr thisWeak_;

          RTCRtpFlexFecCodecParameterSettings();
          virtual ~RTCRtpFlexFecCodecParameterSettings();

          // methods RTCRtpFlexFecCodecCapabilityParameters
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;

          // methods RTCRtpFlexFecCodecParameterSettings
          virtual void wrapper_init_org_ortc_RTCRtpFlexFecCodecParameterSettings() override;
          virtual void wrapper_init_org_ortc_RTCRtpFlexFecCodecParameterSettings(wrapper::org::ortc::RTCRtpFlexFecCodecParameterSettingsPtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtpFlexFecCodecParameterSettings(wrapper::org::ortc::JsonPtr json) override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

