// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCSrtpSdesCryptoParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCSrtpSdesCryptoParameters : public wrapper::org::ortc::RTCSrtpSdesCryptoParameters
        {
          RTCSrtpSdesCryptoParametersWeakPtr thisWeak_;

          RTCSrtpSdesCryptoParameters();
          virtual ~RTCSrtpSdesCryptoParameters();

          // methods RTCSrtpSdesCryptoParameters
          virtual void wrapper_init_org_ortc_RTCSrtpSdesCryptoParameters() override;
          virtual void wrapper_init_org_ortc_RTCSrtpSdesCryptoParameters(wrapper::org::ortc::RTCSrtpSdesCryptoParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCSrtpSdesCryptoParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

