// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCSctpTransportStateChangeEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCSctpTransportStateChangeEvent : public wrapper::org::ortc::RTCSctpTransportStateChangeEvent
        {
          RTCSctpTransportStateChangeEventWeakPtr thisWeak_;

          RTCSctpTransportStateChangeEvent();
          virtual ~RTCSctpTransportStateChangeEvent();

          // properties RTCSctpTransportStateChangeEvent
          virtual wrapper::org::ortc::RTCSctpTransportState get_state() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

