// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_ConstrainStringParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct ConstrainStringParameters : public wrapper::org::ortc::ConstrainStringParameters
        {
          ConstrainStringParametersWeakPtr thisWeak_;

          ConstrainStringParameters();
          virtual ~ConstrainStringParameters();

          // methods ConstrainStringParameters
          virtual void wrapper_init_org_ortc_ConstrainStringParameters() override;
          virtual void wrapper_init_org_ortc_ConstrainStringParameters(wrapper::org::ortc::ConstrainStringParametersPtr source) override;
          virtual void wrapper_init_org_ortc_ConstrainStringParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

