// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCSrtpSdesTransportLifetimeRemainingEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCSrtpSdesTransportLifetimeRemainingEvent : public wrapper::org::ortc::RTCSrtpSdesTransportLifetimeRemainingEvent
        {
          RTCSrtpSdesTransportLifetimeRemainingEventWeakPtr thisWeak_;

          RTCSrtpSdesTransportLifetimeRemainingEvent();
          virtual ~RTCSrtpSdesTransportLifetimeRemainingEvent();

          // properties RTCSrtpSdesTransportLifetimeRemainingEvent
          virtual unsigned long get_leastLifetimeRemainingPercentageForAllKeys() override;
          virtual unsigned long get_overallLifetimeRemainingPercentage() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

