// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_MessageQueue.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct MessageQueue : public wrapper::org::ortc::MessageQueue
        {
          MessageQueueWeakPtr thisWeak_;

          MessageQueue();
          virtual ~MessageQueue();
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

