// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCIdentityResult.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCIdentityResult : public wrapper::org::ortc::RTCIdentityResult
        {
          RTCIdentityResultWeakPtr thisWeak_;

          RTCIdentityResult();
          virtual ~RTCIdentityResult();
          virtual void wrapper_init_org_ortc_RTCIdentityResult() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

