// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCDtlsFingerprint.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCDtlsFingerprint::RTCDtlsFingerprint()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCDtlsFingerprintPtr wrapper::org::ortc::RTCDtlsFingerprint::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCDtlsFingerprint>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCDtlsFingerprint::~RTCDtlsFingerprint()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCDtlsFingerprint::wrapper_init_org_ortc_RTCDtlsFingerprint()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCDtlsFingerprint::wrapper_init_org_ortc_RTCDtlsFingerprint(wrapper::org::ortc::RTCDtlsFingerprintPtr source)
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCDtlsFingerprint::wrapper_init_org_ortc_RTCDtlsFingerprint(wrapper::org::ortc::JsonPtr json)
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::JsonPtr wrapper::impl::org::ortc::RTCDtlsFingerprint::toJson()
{
  wrapper::org::ortc::JsonPtr result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::ortc::RTCDtlsFingerprint::hash()
{
  String result {};
  return result;
}


