// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCSrtpSdesTransportLifetimeRemainingEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCSrtpSdesTransportLifetimeRemainingEvent : public wrapper::org::ortc::RTCSrtpSdesTransportLifetimeRemainingEvent
        {
          RTCSrtpSdesTransportLifetimeRemainingEventWeakPtr thisWeak_;

          RTCSrtpSdesTransportLifetimeRemainingEvent();
          virtual ~RTCSrtpSdesTransportLifetimeRemainingEvent();
          virtual void wrapper_init_org_ortc_RTCSrtpSdesTransportLifetimeRemainingEvent() override;

          // properties RTCSrtpSdesTransportLifetimeRemainingEvent
          virtual wrapper::org::ortc::RTCSrtpSdesTransportLifetimeRemainingPtr get_data() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

