// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpOpusCodecCapabilityParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpOpusCodecCapabilityParameters : public wrapper::org::ortc::RTCRtpOpusCodecCapabilityParameters
        {
          RTCRtpOpusCodecCapabilityParametersWeakPtr thisWeak_;

          RTCRtpOpusCodecCapabilityParameters();
          virtual ~RTCRtpOpusCodecCapabilityParameters();

          // methods RTCRtpOpusCodecCapabilityParameters
          virtual void wrapper_init_org_ortc_RTCRtpOpusCodecCapabilityParameters() override;
          virtual void wrapper_init_org_ortc_RTCRtpOpusCodecCapabilityParameters(wrapper::org::ortc::RTCRtpOpusCodecCapabilityParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtpOpusCodecCapabilityParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

