// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_Dispatcher.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct Dispatcher : public wrapper::org::ortc::Dispatcher
        {
          DispatcherWeakPtr thisWeak_;

          Dispatcher();
          virtual ~Dispatcher();

          // methods Dispatcher
          virtual void wrapper_init_org_ortc_Dispatcher(AnyPtr source) override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

