// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_adapter_RTCSessionDescriptionConnectionDataDetails.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {
        namespace adapter {

          struct RTCSessionDescriptionConnectionDataDetails : public wrapper::org::ortc::adapter::RTCSessionDescriptionConnectionDataDetails
          {
            RTCSessionDescriptionConnectionDataDetailsWeakPtr thisWeak_;

            RTCSessionDescriptionConnectionDataDetails();
            virtual ~RTCSessionDescriptionConnectionDataDetails();

            // methods RTCSessionDescriptionConnectionDataDetails
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionConnectionDataDetails() override;
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionConnectionDataDetails(wrapper::org::ortc::adapter::RTCSessionDescriptionConnectionDataDetailsPtr source) override;
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionConnectionDataDetails(wrapper::org::ortc::JsonPtr json) override;
            virtual wrapper::org::ortc::JsonPtr toJson() override;
            virtual String hash() override;
          };

        } // adapter
      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

