// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_MediaTrackCapabilities.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct MediaTrackCapabilities : public wrapper::org::ortc::MediaTrackCapabilities
        {
          MediaTrackCapabilitiesWeakPtr thisWeak_;

          MediaTrackCapabilities();
          virtual ~MediaTrackCapabilities();

          // methods MediaTrackCapabilities
          virtual void wrapper_init_org_ortc_MediaTrackCapabilities() override;
          virtual void wrapper_init_org_ortc_MediaTrackCapabilities(wrapper::org::ortc::MediaTrackCapabilitiesPtr source) override;
          virtual void wrapper_init_org_ortc_MediaTrackCapabilities(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

