// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpRtxCodecCapabilityParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpRtxCodecCapabilityParameters : public wrapper::org::ortc::RTCRtpRtxCodecCapabilityParameters
        {
          RTCRtpRtxCodecCapabilityParametersWeakPtr thisWeak_;

          RTCRtpRtxCodecCapabilityParameters();
          virtual ~RTCRtpRtxCodecCapabilityParameters();

          // methods RTCRtpRtxCodecCapabilityParameters
          virtual void wrapper_init_org_ortc_RTCRtpRtxCodecCapabilityParameters() override;
          virtual void wrapper_init_org_ortc_RTCRtpRtxCodecCapabilityParameters(wrapper::org::ortc::RTCRtpRtxCodecCapabilityParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtpRtxCodecCapabilityParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

