// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpTransport.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpTransport : public wrapper::org::ortc::RTCRtpTransport
        {
          RTCRtpTransportWeakPtr thisWeak_;

          RTCRtpTransport();
          virtual ~RTCRtpTransport();
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

