// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpHeaderExtensionParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpHeaderExtensionParameters : public wrapper::org::ortc::RTCRtpHeaderExtensionParameters
        {
          RTCRtpHeaderExtensionParametersWeakPtr thisWeak_;

          RTCRtpHeaderExtensionParameters();
          virtual ~RTCRtpHeaderExtensionParameters();

          // methods RTCRtpHeaderExtensionParameters
          virtual void wrapper_init_org_ortc_RTCRtpHeaderExtensionParameters() override;
          virtual void wrapper_init_org_ortc_RTCRtpHeaderExtensionParameters(wrapper::org::ortc::RTCRtpHeaderExtensionParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtpHeaderExtensionParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

