// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_StringOrStringList.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct StringOrStringList : public wrapper::org::ortc::StringOrStringList
        {
          StringOrStringListWeakPtr thisWeak_;

          StringOrStringList();
          virtual ~StringOrStringList();

          // methods StringOrStringList
          virtual void wrapper_init_org_ortc_StringOrStringList() override;
          virtual void wrapper_init_org_ortc_StringOrStringList(wrapper::org::ortc::StringOrStringListPtr source) override;
          virtual void wrapper_init_org_ortc_StringOrStringList(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

