// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_adapter_RTCSessionDescriptionMediaLine.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {
        namespace adapter {

          struct RTCSessionDescriptionMediaLine : public wrapper::org::ortc::adapter::RTCSessionDescriptionMediaLine
          {
            RTCSessionDescriptionMediaLineWeakPtr thisWeak_;

            RTCSessionDescriptionMediaLine();
            virtual ~RTCSessionDescriptionMediaLine();

            // methods RTCSessionDescriptionMediaLine
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionMediaLine() override;
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionMediaLine(wrapper::org::ortc::adapter::RTCSessionDescriptionMediaLinePtr source) override;
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionMediaLine(wrapper::org::ortc::JsonPtr json) override;
            virtual wrapper::org::ortc::JsonPtr toJson() override;
            virtual String hash() override;
          };

        } // adapter
      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

