// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_MediaStreamConstraints.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct MediaStreamConstraints : public wrapper::org::ortc::MediaStreamConstraints
        {
          MediaStreamConstraintsWeakPtr thisWeak_;

          MediaStreamConstraints();
          virtual ~MediaStreamConstraints();

          // methods MediaStreamConstraints
          virtual void wrapper_init_org_ortc_MediaStreamConstraints() override;
          virtual void wrapper_init_org_ortc_MediaStreamConstraints(wrapper::org::ortc::MediaStreamConstraintsPtr source) override;
          virtual void wrapper_init_org_ortc_MediaStreamConstraints(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

