// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_adapter_RTCSessionDescriptionConnectionData.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {
        namespace adapter {

          struct RTCSessionDescriptionConnectionData : public wrapper::org::ortc::adapter::RTCSessionDescriptionConnectionData
          {
            RTCSessionDescriptionConnectionDataWeakPtr thisWeak_;

            RTCSessionDescriptionConnectionData();
            virtual ~RTCSessionDescriptionConnectionData();

            // methods RTCSessionDescriptionConnectionData
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionConnectionData() override;
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionConnectionData(wrapper::org::ortc::adapter::RTCSessionDescriptionConnectionDataPtr source) override;
            virtual void wrapper_init_org_ortc_adapter_RTCSessionDescriptionConnectionData(wrapper::org::ortc::JsonPtr json) override;
            virtual wrapper::org::ortc::JsonPtr toJson() override;
            virtual String hash() override;
          };

        } // adapter
      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

