// Generated by zsLibEventingTool

#include "impl_org_ortc_DoubleRange.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWith;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::DoubleRange::DoubleRange()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::DoubleRangePtr wrapper::org::ortc::DoubleRange::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::DoubleRange>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::DoubleRange::~DoubleRange()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::DoubleRange::wrapper_init_org_ortc_DoubleRange()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::DoubleRange::wrapper_init_org_ortc_DoubleRange(long value)
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::DoubleRange::wrapper_init_org_ortc_DoubleRange(
  long min,
  long max
  )
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::DoubleRange::wrapper_init_org_ortc_DoubleRange(wrapper::org::ortc::JsonPtr json)
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::JsonPtr wrapper::impl::org::ortc::DoubleRange::toJson()
{
  wrapper::org::ortc::JsonPtr result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::ortc::DoubleRange::hash()
{
  String result {};
  return result;
}


