// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCDtlsTransportStateChangeEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCDtlsTransportStateChangeEvent : public wrapper::org::ortc::RTCDtlsTransportStateChangeEvent
        {
          RTCDtlsTransportStateChangeEventWeakPtr thisWeak_;

          RTCDtlsTransportStateChangeEvent();
          virtual ~RTCDtlsTransportStateChangeEvent();
          virtual void wrapper_init_org_ortc_RTCDtlsTransportStateChangeEvent() override;

          // properties RTCDtlsTransportStateChangeEvent
          virtual wrapper::org::ortc::RTCDtlsTransportState get_state() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

