// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_adapter_RTCIceCandidate.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {
        namespace adapter {

          struct RTCIceCandidate : public wrapper::org::ortc::adapter::RTCIceCandidate
          {
            RTCIceCandidateWeakPtr thisWeak_;

            RTCIceCandidate();
            virtual ~RTCIceCandidate();

            // methods RTCIceCandidate
            virtual void wrapper_init_org_ortc_adapter_RTCIceCandidate() override;
            virtual void wrapper_init_org_ortc_adapter_RTCIceCandidate(wrapper::org::ortc::adapter::RTCIceCandidatePtr source) override;
            virtual void wrapper_init_org_ortc_adapter_RTCIceCandidate(wrapper::org::ortc::JsonPtr json) override;
            virtual String toSdp() override;
            virtual wrapper::org::ortc::JsonPtr toJson() override;
            virtual String hash() override;

            // properties RTCIceCandidate
            virtual String get_sdpMid() override;
            virtual void set_sdpMid(String value) override;
          };

        } // adapter
      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

