// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCMessageEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCMessageEvent : public wrapper::org::ortc::RTCMessageEvent
        {
          RTCMessageEventWeakPtr thisWeak_;

          RTCMessageEvent();
          virtual ~RTCMessageEvent();
          virtual void wrapper_init_org_ortc_RTCMessageEvent() override;

          // properties RTCMessageEvent
          virtual wrapper::org::ortc::RTCMessageEventDataPtr get_data() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

