// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_MediaDeviceInfo.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct MediaDeviceInfo : public wrapper::org::ortc::MediaDeviceInfo
        {
          MediaDeviceInfoWeakPtr thisWeak_;

          MediaDeviceInfo();
          virtual ~MediaDeviceInfo();

          // methods MediaDeviceInfo
          virtual void wrapper_init_org_ortc_MediaDeviceInfo() override;
          virtual void wrapper_init_org_ortc_MediaDeviceInfo(wrapper::org::ortc::MediaDeviceInfoPtr source) override;
          virtual void wrapper_init_org_ortc_MediaDeviceInfo(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

