// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCIceTransportController.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCIceTransportController : public wrapper::org::ortc::RTCIceTransportController
        {
          RTCIceTransportControllerWeakPtr thisWeak_;

          RTCIceTransportController();
          virtual ~RTCIceTransportController();

          // methods RTCIceTransportController
          virtual void wrapper_init_org_ortc_RTCIceTransportController() override;
          virtual void addTransport(wrapper::org::ortc::RTCIceTransportPtr transport) override;
          virtual void addTransport(
            wrapper::org::ortc::RTCIceTransportPtr transport,
            uint64_t index
            ) override;

          // properties RTCIceTransportController
          virtual uint64_t get_objectId() override;
          virtual shared_ptr< list< wrapper::org::ortc::RTCIceTransportPtr > > get_transports() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

