// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpCodecCapabilityOptions.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpCodecCapabilityOptions : public wrapper::org::ortc::RTCRtpCodecCapabilityOptions
        {
          RTCRtpCodecCapabilityOptionsWeakPtr thisWeak_;

          RTCRtpCodecCapabilityOptions();
          virtual ~RTCRtpCodecCapabilityOptions();
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

