// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpContributingSource.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpContributingSource : public wrapper::org::ortc::RTCRtpContributingSource
        {
          RTCRtpContributingSourceWeakPtr thisWeak_;

          RTCRtpContributingSource();
          virtual ~RTCRtpContributingSource();

          // methods RTCRtpContributingSource
          virtual void wrapper_init_org_ortc_RTCRtpContributingSource() override;
          virtual void wrapper_init_org_ortc_RTCRtpContributingSource(wrapper::org::ortc::RTCRtpContributingSourcePtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtpContributingSource(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

