// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_MediaTrackConstraints.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct MediaTrackConstraints : public wrapper::org::ortc::MediaTrackConstraints
        {
          MediaTrackConstraintsWeakPtr thisWeak_;

          MediaTrackConstraints();
          virtual ~MediaTrackConstraints();

          // methods MediaTrackConstraintSet
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;

          // methods MediaTrackConstraints
          virtual void wrapper_init_org_ortc_MediaTrackConstraints() override;
          virtual void wrapper_init_org_ortc_MediaTrackConstraints(wrapper::org::ortc::MediaTrackConstraintsPtr source) override;
          virtual void wrapper_init_org_ortc_MediaTrackConstraints(wrapper::org::ortc::JsonPtr json) override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

