// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCSctpTransportListenerEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCSctpTransportListenerEvent : public wrapper::org::ortc::RTCSctpTransportListenerEvent
        {
          RTCSctpTransportListenerEventWeakPtr thisWeak_;

          RTCSctpTransportListenerEvent();
          virtual ~RTCSctpTransportListenerEvent();

          // properties RTCSctpTransportListenerEvent
          virtual wrapper::org::ortc::RTCSctpTransportPtr get_transport() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

