// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCSrtpSdesCryptoParameters.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters::RTCSrtpSdesCryptoParameters()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCSrtpSdesCryptoParametersPtr wrapper::org::ortc::RTCSrtpSdesCryptoParameters::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters::~RTCSrtpSdesCryptoParameters()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters::wrapper_init_org_ortc_RTCSrtpSdesCryptoParameters()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters::wrapper_init_org_ortc_RTCSrtpSdesCryptoParameters(wrapper::org::ortc::RTCSrtpSdesCryptoParametersPtr source)
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters::wrapper_init_org_ortc_RTCSrtpSdesCryptoParameters(wrapper::org::ortc::JsonPtr json)
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::JsonPtr wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters::toJson()
{
  wrapper::org::ortc::JsonPtr result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::ortc::RTCSrtpSdesCryptoParameters::hash()
{
  String result {};
  return result;
}


