// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_ConstrainLong.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct ConstrainLong : public wrapper::org::ortc::ConstrainLong
        {
          ConstrainLongWeakPtr thisWeak_;

          ConstrainLong();
          virtual ~ConstrainLong();

          // methods ConstrainLong
          virtual void wrapper_init_org_ortc_ConstrainLong() override;
          virtual void wrapper_init_org_ortc_ConstrainLong(wrapper::org::ortc::ConstrainLongPtr source) override;
          virtual void wrapper_init_org_ortc_ConstrainLong(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

