// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCIceCandidateComplete.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCIceCandidateComplete : public wrapper::org::ortc::RTCIceCandidateComplete
        {
          RTCIceCandidateCompleteWeakPtr thisWeak_;

          RTCIceCandidateComplete();
          virtual ~RTCIceCandidateComplete();

          // methods RTCIceGathererCandidate
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;

          // properties RTCIceGathererCandidate
          virtual wrapper::org::ortc::RTCIceComponent get_component() override;
          virtual void wrapper_init_org_ortc_RTCIceCandidateComplete() override;

          // properties RTCIceCandidateComplete
          virtual bool get_complete() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

