// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCDtlsTransport.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCDtlsTransport::RTCDtlsTransport()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCDtlsTransportPtr wrapper::org::ortc::RTCDtlsTransport::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCDtlsTransport>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCDtlsTransport::~RTCDtlsTransport()
{
}

//------------------------------------------------------------------------------
shared_ptr< PromiseWithHolder< wrapper::org::ortc::RTCStatsReportPtr > > wrapper::impl::org::ortc::RTCDtlsTransport::getStats(wrapper::org::ortc::RTCStatsTypeSetPtr statTypes)
{
  shared_ptr< PromiseWithHolder< wrapper::org::ortc::RTCStatsReportPtr > > result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCDtlsTransport::wrapper_init_org_ortc_RTCDtlsTransport(
  wrapper::org::ortc::RTCIceTransportPtr iceTransport,
  shared_ptr< list< wrapper::org::ortc::RTCCertificatePtr > > certificates
  )
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCDtlsParametersPtr wrapper::impl::org::ortc::RTCDtlsTransport::remoteParameters()
{
  wrapper::org::ortc::RTCDtlsParametersPtr result {};
  return result;
}

//------------------------------------------------------------------------------
SecureByteBlockPtr wrapper::impl::org::ortc::RTCDtlsTransport::getRemoteCertificates()
{
  SecureByteBlockPtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCDtlsTransport::start(wrapper::org::ortc::RTCDtlsParametersPtr remoteParameters)
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCDtlsTransport::stop()
{
}

//------------------------------------------------------------------------------
uint64_t wrapper::impl::org::ortc::RTCDtlsTransport::get_objectId()
{
  uint64_t result {};
  return result;
}

//------------------------------------------------------------------------------
shared_ptr< list< wrapper::org::ortc::RTCCertificatePtr > > wrapper::impl::org::ortc::RTCDtlsTransport::get_certificates()
{
  shared_ptr< list< wrapper::org::ortc::RTCCertificatePtr > > result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCIceTransportPtr wrapper::impl::org::ortc::RTCDtlsTransport::get_transport()
{
  wrapper::org::ortc::RTCIceTransportPtr result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCDtlsTransportState wrapper::impl::org::ortc::RTCDtlsTransport::get_state()
{
  wrapper::org::ortc::RTCDtlsTransportState result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCDtlsParametersPtr wrapper::impl::org::ortc::RTCDtlsTransport::get_localParameters()
{
  wrapper::org::ortc::RTCDtlsParametersPtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCDtlsTransport::wrapper_onObserverCountChanged(size_t count)
{
}


