// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCIdentityAssertion.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCIdentityAssertion : public wrapper::org::ortc::RTCIdentityAssertion
        {
          RTCIdentityAssertionWeakPtr thisWeak_;

          RTCIdentityAssertion();
          virtual ~RTCIdentityAssertion();
          virtual void wrapper_init_org_ortc_RTCIdentityAssertion() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

