// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCSctpCapabilities.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCSctpCapabilities : public wrapper::org::ortc::RTCSctpCapabilities
        {
          RTCSctpCapabilitiesWeakPtr thisWeak_;

          RTCSctpCapabilities();
          virtual ~RTCSctpCapabilities();

          // methods RTCSctpCapabilities
          virtual void wrapper_init_org_ortc_RTCSctpCapabilities() override;
          virtual void wrapper_init_org_ortc_RTCSctpCapabilities(wrapper::org::ortc::RTCSctpCapabilitiesPtr source) override;
          virtual void wrapper_init_org_ortc_RTCSctpCapabilities(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

