// Generated by zsLibEventingTool

#include "impl_org_ortc_OverconstrainedErrorEvent.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWith;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::OverconstrainedErrorEvent::OverconstrainedErrorEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::OverconstrainedErrorEventPtr wrapper::org::ortc::OverconstrainedErrorEvent::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::OverconstrainedErrorEvent>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::OverconstrainedErrorEvent::~OverconstrainedErrorEvent()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::OverconstrainedErrorEvent::wrapper_init_org_ortc_OverconstrainedErrorEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::OverconstrainedErrorPtr wrapper::impl::org::ortc::OverconstrainedErrorEvent::get_error()
{
  wrapper::org::ortc::OverconstrainedErrorPtr result {};
  return result;
}


