// Generated by zsLibEventingTool

#include "impl_org_ortc_ErrorEvent.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWith;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::ErrorEvent::ErrorEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::ErrorEventPtr wrapper::org::ortc::ErrorEvent::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::ErrorEvent>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::ErrorEvent::~ErrorEvent()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::ErrorEvent::wrapper_init_org_ortc_ErrorEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::ErrorPtr wrapper::impl::org::ortc::ErrorEvent::get_error()
{
  wrapper::org::ortc::ErrorPtr result {};
  return result;
}


