// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCDataChannelEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCDataChannelEvent : public wrapper::org::ortc::RTCDataChannelEvent
        {
          RTCDataChannelEventWeakPtr thisWeak_;

          RTCDataChannelEvent();
          virtual ~RTCDataChannelEvent();
          virtual void wrapper_init_org_ortc_RTCDataChannelEvent() override;

          // properties RTCDataChannelEvent
          virtual wrapper::org::ortc::RTCDataChannelPtr get_dataChannel() override;
          virtual void set_dataChannel(wrapper::org::ortc::RTCDataChannelPtr value) override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

