// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCIceGathererIceErrorEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCIceGathererIceErrorEvent : public wrapper::org::ortc::RTCIceGathererIceErrorEvent
        {
          RTCIceGathererIceErrorEventWeakPtr thisWeak_;

          RTCIceGathererIceErrorEvent();
          virtual ~RTCIceGathererIceErrorEvent();
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

