// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpListener.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpListener : public wrapper::org::ortc::RTCRtpListener
        {
          RTCRtpListenerWeakPtr thisWeak_;

          RTCRtpListener();
          virtual ~RTCRtpListener();

          // methods RTCStatsProvider
          virtual shared_ptr< PromiseWith< wrapper::org::ortc::RTCStatsReportPtr > > getStats(wrapper::org::ortc::RTCStatsTypeSetPtr statTypes) override;

          // methods RTCRtpListener
          virtual void wrapper_init_org_ortc_RTCRtpListener(wrapper::org::ortc::RTCRtpTransportPtr transport) override;
          virtual void wrapper_init_org_ortc_RTCRtpListener(
            wrapper::org::ortc::RTCRtpTransportPtr transport,
            shared_ptr< list< wrapper::org::ortc::RTCRtpHeaderExtensionParametersPtr > > headerExtensions
            ) override;
          virtual void setHeaderExtensions(shared_ptr< list< wrapper::org::ortc::RTCRtpHeaderExtensionParametersPtr > > headerExtensions) override;

          // properties RTCRtpListener
          virtual uint64_t get_objectId() override;
          virtual wrapper::org::ortc::RTCRtpTransportPtr get_transport() override;

          virtual void wrapper_onObserverCountChanged(size_t count) override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

