// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCMessageEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCMessageEvent : public wrapper::org::ortc::RTCMessageEvent
        {
          RTCMessageEventWeakPtr thisWeak_;

          RTCMessageEvent();
          virtual ~RTCMessageEvent();

          // properties RTCMessageEvent
          virtual SecureByteBlockPtr get_binary() override;
          virtual String get_text() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

