// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCIceTransportController.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCIceTransportController::RTCIceTransportController()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCIceTransportControllerPtr wrapper::org::ortc::RTCIceTransportController::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCIceTransportController>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCIceTransportController::~RTCIceTransportController()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCIceTransportController::wrapper_init_org_ortc_RTCIceTransportController()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCIceTransportController::addTransport(wrapper::org::ortc::RTCIceTransportPtr transport)
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCIceTransportController::addTransport(
  wrapper::org::ortc::RTCIceTransportPtr transport,
  uint64_t index
  )
{
}

//------------------------------------------------------------------------------
uint64_t wrapper::impl::org::ortc::RTCIceTransportController::get_objectId()
{
  uint64_t result {};
  return result;
}

//------------------------------------------------------------------------------
shared_ptr< list< wrapper::org::ortc::RTCIceTransportPtr > > wrapper::impl::org::ortc::RTCIceTransportController::get_transports()
{
  shared_ptr< list< wrapper::org::ortc::RTCIceTransportPtr > > result {};
  return result;
}


