// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_OverconstrainedError.h"

#include <ortc/IMediaStreamTrack.h>

namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct OverconstrainedError : public wrapper::org::ortc::OverconstrainedError
        {
          ZS_DECLARE_TYPEDEF_PTR(::ortc::IMediaStreamTrackTypes::OverconstrainedError, NativeType);
          ZS_DECLARE_TYPEDEF_PTR(OverconstrainedError, WrapperImplType);
          ZS_DECLARE_TYPEDEF_PTR(wrapper::org::ortc::OverconstrainedError, WrapperType);
          OverconstrainedErrorWeakPtr thisWeak_;

          OverconstrainedError();
          virtual ~OverconstrainedError();
          virtual void wrapper_init_org_ortc_OverconstrainedError() override;

          static WrapperImplTypePtr toWrapper(NativeTypePtr native);
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

