// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCSsrcConflictEvent.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWith;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCSsrcConflictEvent::RTCSsrcConflictEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCSsrcConflictEventPtr wrapper::org::ortc::RTCSsrcConflictEvent::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCSsrcConflictEvent>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCSsrcConflictEvent::~RTCSsrcConflictEvent()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCSsrcConflictEvent::wrapper_init_org_ortc_RTCSsrcConflictEvent()
{
}

//------------------------------------------------------------------------------
uint32_t wrapper::impl::org::ortc::RTCSsrcConflictEvent::get_ssrc()
{
  uint32_t result {};
  return result;
}


