// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCMessageEventData.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCMessageEventData : public wrapper::org::ortc::RTCMessageEventData
        {
          RTCMessageEventDataWeakPtr thisWeak_;

          RTCMessageEventData();
          virtual ~RTCMessageEventData();
          virtual void wrapper_init_org_ortc_RTCMessageEventData() override;

          // properties RTCMessageEventData
          virtual SecureByteBlockPtr get_binary() override;
          virtual String get_text() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

