// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpFlexFecCodecCapabilityParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpFlexFecCodecCapabilityParameters : public wrapper::org::ortc::RTCRtpFlexFecCodecCapabilityParameters
        {
          RTCRtpFlexFecCodecCapabilityParametersWeakPtr thisWeak_;

          RTCRtpFlexFecCodecCapabilityParameters();
          virtual ~RTCRtpFlexFecCodecCapabilityParameters();

          // methods RTCRtpFlexFecCodecCapabilityParameters
          virtual void wrapper_init_org_ortc_RTCRtpFlexFecCodecCapabilityParameters() override;
          virtual void wrapper_init_org_ortc_RTCRtpFlexFecCodecCapabilityParameters(wrapper::org::ortc::RTCRtpFlexFecCodecCapabilityParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtpFlexFecCodecCapabilityParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;

          // properties RTCRtpFlexFecCodecCapabilityParameters
          virtual ::zsLib::Microseconds get_repairWindow() override;
          virtual void set_repairWindow(::zsLib::Microseconds value) override;
          virtual Optional< unsigned long > get_l() override;
          virtual void set_l(Optional< unsigned long > value) override;
          virtual Optional< unsigned long > get_d() override;
          virtual void set_d(Optional< unsigned long > value) override;
          virtual Optional< wrapper::org::ortc::RTCRtpFlexFecCodecCapabilityParametersToP > get_toP() override;
          virtual void set_toP(Optional< wrapper::org::ortc::RTCRtpFlexFecCodecCapabilityParametersToP > value) override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

