// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCStatsReport.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCStatsReport : public wrapper::org::ortc::RTCStatsReport
        {
          RTCStatsReportWeakPtr thisWeak_;

          RTCStatsReport();
          virtual ~RTCStatsReport();

          // methods RTCStatsReport
          virtual wrapper::org::ortc::RTCStatsPtr getStats(String id) override;
          virtual void wrapper_init_org_ortc_RTCStatsReport() override;

          // properties RTCStatsReport
          virtual uint64_t get_objectId() override;
          virtual shared_ptr< list< String > > get_statsIds() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

