// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCDataTransport.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCDataTransport : public wrapper::org::ortc::RTCDataTransport
        {
          RTCDataTransportWeakPtr thisWeak_;

          RTCDataTransport();
          virtual ~RTCDataTransport();
          virtual void wrapper_init_org_ortc_RTCDataTransport() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

