// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCIceTransportStateChangeEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCIceTransportStateChangeEvent : public wrapper::org::ortc::RTCIceTransportStateChangeEvent
        {
          RTCIceTransportStateChangeEventWeakPtr thisWeak_;

          RTCIceTransportStateChangeEvent();
          virtual ~RTCIceTransportStateChangeEvent();

          // properties RTCIceTransportStateChangeEvent
          virtual wrapper::org::ortc::RTCIceTransportState get_state() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

