// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtcpParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtcpParameters : public wrapper::org::ortc::RTCRtcpParameters
        {
          RTCRtcpParametersWeakPtr thisWeak_;

          RTCRtcpParameters();
          virtual ~RTCRtcpParameters();

          // methods RTCRtcpParameters
          virtual void wrapper_init_org_ortc_RTCRtcpParameters() override;
          virtual void wrapper_init_org_ortc_RTCRtcpParameters(wrapper::org::ortc::RTCRtcpParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtcpParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

