// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_Error.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct Error : public wrapper::org::ortc::Error
        {
          ErrorWeakPtr thisWeak_;

          Error();
          virtual ~Error();
          virtual void wrapper_init_org_ortc_Error() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

