// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCDtlsParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCDtlsParameters : public wrapper::org::ortc::RTCDtlsParameters
        {
          RTCDtlsParametersWeakPtr thisWeak_;

          RTCDtlsParameters();
          virtual ~RTCDtlsParameters();

          // methods RTCDtlsParameters
          virtual void wrapper_init_org_ortc_RTCDtlsParameters() override;
          virtual void wrapper_init_org_ortc_RTCDtlsParameters(wrapper::org::ortc::RTCDtlsParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCDtlsParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

