// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_adapter_RTCPeerConnection.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {
        namespace adapter {

          struct RTCPeerConnection : public wrapper::org::ortc::adapter::RTCPeerConnection
          {
            RTCPeerConnectionWeakPtr thisWeak_;

            RTCPeerConnection();
            virtual ~RTCPeerConnection();

            // methods RTCStatsProvider
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::RTCStatsReportPtr > > getStats(wrapper::org::ortc::RTCStatsTypeSetPtr statTypes) override;

            // methods RTCPeerConnection
            virtual void wrapper_init_org_ortc_adapter_RTCPeerConnection() override;
            virtual void wrapper_init_org_ortc_adapter_RTCPeerConnection(wrapper::org::ortc::adapter::RTCConfigurationPtr configuration) override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::adapter::RTCSessionDescriptionPtr > > createOffer() override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::adapter::RTCSessionDescriptionPtr > > createOffer(wrapper::org::ortc::adapter::RTCOfferOptionsPtr options) override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::adapter::RTCSessionDescriptionPtr > > createAnswer() override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::adapter::RTCSessionDescriptionPtr > > createAnswer(wrapper::org::ortc::adapter::RTCAnswerOptionsPtr options) override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::adapter::RTCSessionDescriptionPtr > > createCapabilities() override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::adapter::RTCSessionDescriptionPtr > > createCapabilities(wrapper::org::ortc::adapter::RTCCapabilityOptionsPtr options) override;
            virtual PromisePtr setLocalDescription(wrapper::org::ortc::adapter::RTCSessionDescriptionPtr description) override;
            virtual PromisePtr setRemoteDescription(wrapper::org::ortc::adapter::RTCSessionDescriptionPtr description) override;
            virtual void addIceCandidate(wrapper::org::ortc::adapter::RTCIceCandidatePtr candidate) override;
            virtual shared_ptr< list< wrapper::org::ortc::RTCIceServerPtr > > getDefaultIceServers() override;
            virtual void close() override;
            virtual shared_ptr< list< wrapper::org::ortc::RTCRtpSenderPtr > > getSenders() override;
            virtual shared_ptr< list< wrapper::org::ortc::RTCRtpReceiverPtr > > getReceivers() override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::RTCRtpSenderPtr > > addTrack(wrapper::org::ortc::MediaStreamTrackPtr track) override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::RTCRtpSenderPtr > > addTrack(
              wrapper::org::ortc::MediaStreamTrackPtr track,
              wrapper::org::ortc::adapter::RTCMediaStreamTrackConfigurationPtr config
              ) override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::RTCRtpSenderPtr > > addTrack(
              wrapper::org::ortc::MediaStreamTrackPtr track,
              shared_ptr< list< wrapper::org::ortc::adapter::MediaStreamPtr > > mediaStreams,
              wrapper::org::ortc::adapter::RTCMediaStreamTrackConfigurationPtr config
              ) override;
            virtual void removeTrack(wrapper::org::ortc::RTCRtpSenderPtr sender) override;
            virtual shared_ptr< PromiseWith< wrapper::org::ortc::RTCDataChannelPtr > > createDataChannel(wrapper::org::ortc::RTCDataChannelParametersPtr parameters) override;

            // properties RTCPeerConnection
            virtual uint64_t get_objectId() override;
            virtual wrapper::org::ortc::adapter::RTCSessionDescriptionPtr get_localDescription() override;
            virtual wrapper::org::ortc::adapter::RTCSessionDescriptionPtr get_currentDescription() override;
            virtual wrapper::org::ortc::adapter::RTCSessionDescriptionPtr get_pendingDescription() override;
            virtual wrapper::org::ortc::adapter::RTCSessionDescriptionPtr get_remoteDescription() override;
            virtual wrapper::org::ortc::adapter::RTCSessionDescriptionPtr get_currentRemoteDescription() override;
            virtual wrapper::org::ortc::adapter::RTCSessionDescriptionPtr get_pendingRemoteDescription() override;
            virtual wrapper::org::ortc::adapter::RTCSignalingState get_signalingState() override;
            virtual wrapper::org::ortc::RTCIceGathererState get_iceGatheringState() override;
            virtual wrapper::org::ortc::adapter::RTCIceConnectionState get_iceConnectionState() override;
            virtual wrapper::org::ortc::adapter::RTCPeerConnectionState get_connectionState() override;
            virtual bool get_canTrickleCandidates() override;
            virtual wrapper::org::ortc::adapter::RTCConfigurationPtr get_getConfiguration() override;
            virtual void set_getConfiguration(wrapper::org::ortc::adapter::RTCConfigurationPtr value) override;

            virtual void wrapper_onObserverCountChanged(size_t count) override;
          };

        } // adapter
      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

