// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCSctpTransportStateChangeEvent.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCSctpTransportStateChangeEvent::RTCSctpTransportStateChangeEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCSctpTransportStateChangeEventPtr wrapper::org::ortc::RTCSctpTransportStateChangeEvent::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCSctpTransportStateChangeEvent>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCSctpTransportStateChangeEvent::~RTCSctpTransportStateChangeEvent()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCSctpTransportStateChangeEvent::wrapper_init_org_ortc_RTCSctpTransportStateChangeEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCSctpTransportState wrapper::impl::org::ortc::RTCSctpTransportStateChangeEvent::get_state()
{
  wrapper::org::ortc::RTCSctpTransportState result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCSctpTransportStateChangeEvent::set_state(wrapper::org::ortc::RTCSctpTransportState value)
{
}


