// Generated by zsLibEventingTool

#include "impl_org_ortc_MediaDevices.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::MediaDevices::MediaDevices()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::MediaDevicesPtr wrapper::org::ortc::MediaDevices::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::MediaDevices>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::MediaDevices::~MediaDevices()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::MediaTrackSupportedConstraintsPtr wrapper::org::ortc::MediaDevices::getSupportedConstraints()
{
  wrapper::org::ortc::MediaTrackSupportedConstraintsPtr result {};
  return result;
}

//------------------------------------------------------------------------------
shared_ptr< PromiseWithHolder< shared_ptr< list< wrapper::org::ortc::MediaDeviceInfoPtr > > > > wrapper::org::ortc::MediaDevices::enumerateDevices()
{
  shared_ptr< PromiseWithHolder< shared_ptr< list< wrapper::org::ortc::MediaDeviceInfoPtr > > > > result {};
  return result;
}

//------------------------------------------------------------------------------
shared_ptr< PromiseWithHolder< shared_ptr< list< wrapper::org::ortc::MediaStreamTrackPtr > > > > wrapper::org::ortc::MediaDevices::getUserMedia(wrapper::org::ortc::MediaStreamConstraintsPtr constraints)
{
  shared_ptr< PromiseWithHolder< shared_ptr< list< wrapper::org::ortc::MediaStreamTrackPtr > > > > result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::MediaDevicesPtr wrapper::org::ortc::MediaDevices::get_singleton()
{
  wrapper::org::ortc::MediaDevicesPtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::MediaDevices::wrapper_onObserverCountChanged(size_t count)
{
}


