// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_LongRange.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct LongRange : public wrapper::org::ortc::LongRange
        {
          LongRangeWeakPtr thisWeak_;

          LongRange();
          virtual ~LongRange();

          // methods LongRange
          virtual void wrapper_init_org_ortc_LongRange() override;
          virtual void wrapper_init_org_ortc_LongRange(long value) override;
          virtual void wrapper_init_org_ortc_LongRange(
            long min,
            long max
            ) override;
          virtual void wrapper_init_org_ortc_LongRange(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

