// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCStatsProvider.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWith;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCStatsProvider::RTCStatsProvider()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCStatsProviderPtr wrapper::org::ortc::RTCStatsProvider::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCStatsProvider>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCStatsProvider::~RTCStatsProvider()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCStatsProvider::wrapper_init_org_ortc_RTCStatsProvider()
{
}

//------------------------------------------------------------------------------
shared_ptr< PromiseWith< wrapper::org::ortc::RTCStatsReportPtr > > wrapper::impl::org::ortc::RTCStatsProvider::getStats(wrapper::org::ortc::RTCStatsTypeSetPtr statTypes)
{
  shared_ptr< PromiseWith< wrapper::org::ortc::RTCStatsReportPtr > > result {};
  return result;
}


