// Generated by zsLibEventingTool

#include "impl_org_ortc_adapter_RTCTrackEvent.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWith;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::adapter::RTCTrackEvent::RTCTrackEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::adapter::RTCTrackEventPtr wrapper::org::ortc::adapter::RTCTrackEvent::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::adapter::RTCTrackEvent>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::adapter::RTCTrackEvent::~RTCTrackEvent()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::adapter::RTCTrackEvent::wrapper_init_org_ortc_adapter_RTCTrackEvent()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCRtpReceiverPtr wrapper::impl::org::ortc::adapter::RTCTrackEvent::get_receiver()
{
  wrapper::org::ortc::RTCRtpReceiverPtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::adapter::RTCTrackEvent::set_receiver(wrapper::org::ortc::RTCRtpReceiverPtr value)
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::MediaStreamTrackPtr wrapper::impl::org::ortc::adapter::RTCTrackEvent::get_track()
{
  wrapper::org::ortc::MediaStreamTrackPtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::adapter::RTCTrackEvent::set_track(wrapper::org::ortc::MediaStreamTrackPtr value)
{
}

//------------------------------------------------------------------------------
shared_ptr< list< wrapper::org::ortc::adapter::MediaStreamPtr > > wrapper::impl::org::ortc::adapter::RTCTrackEvent::get_mediaStreams()
{
  shared_ptr< list< wrapper::org::ortc::adapter::MediaStreamPtr > > result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::adapter::RTCTrackEvent::set_mediaStreams(shared_ptr< list< wrapper::org::ortc::adapter::MediaStreamPtr > > value)
{
}


