// Generated by zsLibEventingTool

#include "impl_org_ortc_adapter_RTCSessionDescription.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWith;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::adapter::RTCSessionDescription::RTCSessionDescription()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::adapter::RTCSessionDescriptionPtr wrapper::org::ortc::adapter::RTCSessionDescription::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::adapter::RTCSessionDescription>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::adapter::RTCSessionDescription::~RTCSessionDescription()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::adapter::RTCSessionDescription::wrapper_init_org_ortc_adapter_RTCSessionDescription(
  wrapper::org::ortc::adapter::RTCSessionDescriptionSignalingType type,
  String description
  )
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::adapter::RTCSessionDescription::wrapper_init_org_ortc_adapter_RTCSessionDescription(
  wrapper::org::ortc::adapter::RTCSessionDescriptionSignalingType type,
  wrapper::org::ortc::adapter::RTCSessionDescriptionDescriptionPtr description
  )
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCRtpParametersPtr wrapper::org::ortc::adapter::RTCSessionDescription::convertCapabilitiesToParameters(wrapper::org::ortc::RTCRtpCapabilitiesPtr capabilitites)
{
  wrapper::org::ortc::RTCRtpParametersPtr result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCRtpCapabilitiesPtr wrapper::org::ortc::adapter::RTCSessionDescription::ConvertParametersToCapabilitites(wrapper::org::ortc::RTCRtpParametersPtr parameters)
{
  wrapper::org::ortc::RTCRtpCapabilitiesPtr result {};
  return result;
}

//------------------------------------------------------------------------------
uint64_t wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_objectId()
{
  uint64_t result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::adapter::RTCSessionDescriptionSignalingType wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_type()
{
  wrapper::org::ortc::adapter::RTCSessionDescriptionSignalingType result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::adapter::RTCSdpType wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_sdpType()
{
  wrapper::org::ortc::adapter::RTCSdpType result {};
  return result;
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_isJsonSignalling()
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
bool wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_isSdpSignaling()
{
  bool result {};
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::ortc::adapter::RTCSessionDescriptionDescriptionPtr wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_description()
{
  wrapper::org::ortc::adapter::RTCSessionDescriptionDescriptionPtr result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_formattedDescription()
{
  String result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::ortc::adapter::RTCSessionDescription::get_sdp()
{
  String result {};
  return result;
}


