// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_adapter_RTCPeerConnectionIceCompleteEvent.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {
        namespace adapter {

          struct RTCPeerConnectionIceCompleteEvent : public wrapper::org::ortc::adapter::RTCPeerConnectionIceCompleteEvent
          {
            RTCPeerConnectionIceCompleteEventWeakPtr thisWeak_;

            RTCPeerConnectionIceCompleteEvent();
            virtual ~RTCPeerConnectionIceCompleteEvent();
            virtual void wrapper_init_org_ortc_adapter_RTCPeerConnectionIceCompleteEvent() override;

            // properties RTCPeerConnectionIceCompleteEvent
            virtual wrapper::org::ortc::RTCIceCandidateCompletePtr get_candidate() override;
            virtual void set_candidate(wrapper::org::ortc::RTCIceCandidateCompletePtr value) override;
          };

        } // adapter
      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

