// Generated by zsLibEventingTool

#include "impl_org_ortc_RTCRtpCapabilities.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCRtpCapabilities::RTCRtpCapabilities()
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::RTCRtpCapabilitiesPtr wrapper::org::ortc::RTCRtpCapabilities::wrapper_create()
{
  auto pThis = make_shared<wrapper::impl::org::ortc::RTCRtpCapabilities>();
  pThis->thisWeak_ = pThis;
  return pThis;
}

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::RTCRtpCapabilities::~RTCRtpCapabilities()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCRtpCapabilities::wrapper_init_org_ortc_RTCRtpCapabilities()
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCRtpCapabilities::wrapper_init_org_ortc_RTCRtpCapabilities(wrapper::org::ortc::RTCRtpCapabilitiesPtr source)
{
}

//------------------------------------------------------------------------------
void wrapper::impl::org::ortc::RTCRtpCapabilities::wrapper_init_org_ortc_RTCRtpCapabilities(wrapper::org::ortc::JsonPtr json)
{
}

//------------------------------------------------------------------------------
wrapper::org::ortc::JsonPtr wrapper::impl::org::ortc::RTCRtpCapabilities::toJson()
{
  wrapper::org::ortc::JsonPtr result {};
  return result;
}

//------------------------------------------------------------------------------
String wrapper::impl::org::ortc::RTCRtpCapabilities::hash()
{
  String result {};
  return result;
}


