// Generated by zsLibEventingTool

#pragma once

#include "types.h"
#include "generated/org_ortc_RTCRtpRtxParameters.h"


namespace wrapper {
  namespace impl {
    namespace org {
      namespace ortc {

        struct RTCRtpRtxParameters : public wrapper::org::ortc::RTCRtpRtxParameters
        {
          RTCRtpRtxParametersWeakPtr thisWeak_;

          RTCRtpRtxParameters();
          virtual ~RTCRtpRtxParameters();

          // methods RTCRtpRtxParameters
          virtual void wrapper_init_org_ortc_RTCRtpRtxParameters() override;
          virtual void wrapper_init_org_ortc_RTCRtpRtxParameters(wrapper::org::ortc::RTCRtpRtxParametersPtr source) override;
          virtual void wrapper_init_org_ortc_RTCRtpRtxParameters(wrapper::org::ortc::JsonPtr json) override;
          virtual wrapper::org::ortc::JsonPtr toJson() override;
          virtual String hash() override;
        };

      } // ortc
    } // org
  } // namespace impl
} // namespace wrapper

