// Generated by zsLibEventingTool

#include "impl_org_ortc_MediaControl.h"

using ::zsLib::String;
using ::zsLib::Optional;
using ::zsLib::Any;
using ::zsLib::AnyPtr;
using ::zsLib::AnyHolder;
using ::zsLib::Promise;
using ::zsLib::PromisePtr;
using ::zsLib::PromiseWithHolder;
using ::zsLib::PromiseWithHolderPtr;
using ::zsLib::eventing::SecureByteBlock;
using ::zsLib::eventing::SecureByteBlockPtr;
using ::std::shared_ptr;
using ::std::weak_ptr;
using ::std::make_shared;
using ::std::list;
using ::std::set;
using ::std::map;

//------------------------------------------------------------------------------
wrapper::impl::org::ortc::MediaControl::~MediaControl()
{
}

//------------------------------------------------------------------------------
AnyPtr wrapper::org::ortc::MediaControl::get_displayOrientation()
{
  AnyPtr result {};
  return result;
}

//------------------------------------------------------------------------------
void wrapper::org::ortc::MediaControl::set_displayOrientation(AnyPtr value)
{
}


