//import "windows.foundation.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace Ortc
    {


        /// <summary>
        /// A message queue for receiving delegate events.
        /// </summary>
        [version(1.0)]
        [uuid(8494c796-81c9-dc99-e460-2de261b993ea)]
        interface IEventQueue : IInspectable
        {
        };

        /// <summary>
        /// A message queue for receiving delegate events.
        /// </summary>
        runtimeclass EventQueue : [default] IEventQueue
        {
            /// <summary>
            /// Cast from Org.Ortc.IEventQueue to Org.Ortc.EventQueue
            /// </summary>
            [default_overload]
            [method_name("CastFromIEventQueue")]
            static Org.Ortc.EventQueue Cast(Org.Ortc.IEventQueue source);

            /// <summary>
            /// The default windows message queue for the system GUI thread.
            /// </summary>
            static Org.Ortc.IEventQueue GetDefaultForUi();

            /// <summary>
            /// Gets or sets the default system dispatcher object.
            /// </summary>
            static Org.Ortc.IEventQueue Singleton { get; set; };
        };

    } // namespace Ortc
} // namespace Org

