// Generated by zsLibEventingTool


#ifndef CX_USE_GENERATED_ORG_WEBRTC_VIDEODEVICEINFO
#include <wrapper/override/cx/Org_WebRtc_VideoDeviceInfo.cpp>
#else // CX_USE_GENERATED_ORG_WEBRTC_VIDEODEVICEINFO
#include "cx_Helpers.h"
#include "Org_WebRtc_VideoDeviceInfo.h"

//------------------------------------------------------------------------------
::Org::WebRtc::VideoDeviceInfo^ Org::WebRtc::VideoDeviceInfo::ToCx(wrapper::org::webRtc::VideoDeviceInfoPtr value)
{
  if (!value) return nullptr;
  auto result = ref new VideoDeviceInfo(WrapperCreate{});
  result->native_ = value;
  return result;
}

//------------------------------------------------------------------------------
wrapper::org::webRtc::VideoDeviceInfoPtr Org::WebRtc::VideoDeviceInfo::FromCx(::Org::WebRtc::VideoDeviceInfo^ value)
{
  if (nullptr == value) return wrapper::org::webRtc::VideoDeviceInfoPtr();
  return value->native_;
}

//------------------------------------------------------------------------------
Org::WebRtc::VideoDeviceInfo::VideoDeviceInfo()
  : native_(wrapper::org::webRtc::VideoDeviceInfo::wrapper_create())
{
  native_->wrapper_init_org_webRtc_VideoDeviceInfo();
}

//------------------------------------------------------------------------------
Platform::Object^ Org::WebRtc::VideoDeviceInfo::Info::get()
{
  if (!native_) {throw ref new Platform::NullReferenceException();}
  return ::Internal::Helper::ToCx(native_->get_info());
}


#endif //ifndef CX_USE_GENERATED_ORG_WEBRTC_VIDEODEVICEINFO
