// Generated by zsLibEventingTool


#ifndef CX_USE_GENERATED_ORG_WEBRTC_VIDEODEVICEINFO
#include <wrapper/override/cx/Org_WebRtc_VideoDeviceInfo.h>
#else // CX_USE_GENERATED_ORG_WEBRTC_VIDEODEVICEINFO

#pragma once

#include "types.h"
#include <wrapper/generated/org_webRtc_VideoDeviceInfo.h>

namespace Org {
  namespace WebRtc {



    public ref class VideoDeviceInfo sealed
    {
    internal:
      wrapper::org::webRtc::VideoDeviceInfoPtr native_;

      struct WrapperCreate {};
      VideoDeviceInfo(const WrapperCreate &) {}

      static VideoDeviceInfo^ ToCx(wrapper::org::webRtc::VideoDeviceInfoPtr value);
      static wrapper::org::webRtc::VideoDeviceInfoPtr FromCx(VideoDeviceInfo^ value);



    public:
      VideoDeviceInfo();
      property Platform::Object^ Info { Platform::Object^ get(); }

    };

  } // namespace WebRtc
} // namespace Org
#endif //ifndef CX_USE_GENERATED_ORG_WEBRTC_VIDEODEVICEINFO
