//import "windows.foundation.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        /// <summary>
        /// MediaSource represents an object holder for a platform specific
        /// media source.
        /// </summary>
        [version(1.0)]
        [uuid(1c5627cf-8a22-f886-578a-8f7b872ef42d)]
        interface IMediaSource : IInspectable
        {

            /// <summary>
            /// Gets the platform specific media source.
            /// </summary>
            Windows.Media.Core.IMediaSource Source { get; };
        };

        /// <summary>
        /// MediaSource represents an object holder for a platform specific
        /// media source.
        /// </summary>
        runtimeclass MediaSource : [default] IMediaSource
        {

            /// <summary>
            /// Constructs a media source object from a native media source
            /// type.
            /// </summary>
            [method_name("MediaSourceWithNativeSource")]
            [default_overload]
            MediaSource(Windows.Media.Core.IMediaSource Source);

            /// <summary>
            /// Cast from Org.WebRtc.IMediaSource to Org.WebRtc.MediaSource
            /// </summary>
            [default_overload]
            [method_name("CastFromIMediaSource")]
            static Org.WebRtc.MediaSource Cast(Org.WebRtc.IMediaSource source);
        };

    } // namespace WebRtc
} // namespace Org

