//import "windows.foundation.customattributes.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        [version(1.0)]
        [uuid(de70609e-604d-5ced-6090-d3891021c4f4)]
        [webhosthidden]
        interface IEventQueueMaker : IInspectable
        {
        };

        [webhosthidden]
        runtimeclass EventQueueMaker : [default] IEventQueueMaker
        {

            /// <summary>
            /// Cast from Org.WebRtc.IEventQueueMaker to Org.WebRtc.EventQueueMaker
            /// </summary>
            [default_overload]
            [method_name("CastFromIEventQueueMaker")]
            static Org.WebRtc.EventQueueMaker Cast(Org.WebRtc.IEventQueueMaker source);

            /// <summary>
            /// Creates an event queue object from a native queue type.
            /// </summary>
            static Org.WebRtc.IEventQueue Bind(Windows.UI.Core.CoreDispatcher Queue);

            /// <summary>
            /// Extracts a native queue from an event queue object.
            /// </summary>
            static Windows.UI.Core.CoreDispatcher Extract(Org.WebRtc.IEventQueue Queue);
        };

    } // namespace WebRtc
} // namespace Org

