//import "windows.foundation.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        /// <summary>
        /// MediaSource represents an object holder for a platform specific
        /// media element.
        /// </summary>
        [version(1.0)]
        [uuid(dcbb7685-ecf3-119e-a677-61d3379e6b5f)]
        interface IMediaElement : IInspectable
        {

        };

        /// <summary>
        /// MediaSource represents an object holder for a platform specific
        /// media element.
        /// </summary>
        runtimeclass MediaElement : [default] IMediaElement
        {

            /// <summary>
            /// Cast from Org.WebRtc.IMediaElement to Org.WebRtc.MediaElement
            /// </summary>
            [default_overload]
            [method_name("CastFromIMediaElement")]
            static Org.WebRtc.MediaElement Cast(Org.WebRtc.IMediaElement source);
        };

    } // namespace WebRtc
} // namespace Org

