//import "windows.foundation.customattributes.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        [version(1.0)]
        [uuid(d88e3313-bef8-0322-946d-ef9488c487fd)]
        [webhosthidden]
        interface IMediaElementMaker : IInspectable
        {
        };

        [webhosthidden]
        runtimeclass MediaElementMaker : [default] IMediaElementMaker
        {

            /// <summary>
            /// Cast from Org.WebRtc.IMediaElementMaker to Org.WebRtc.MediaElementMaker
            /// </summary>
            [default_overload]
            [method_name("CastFromIMediaElementMaker")]
            static Org.WebRtc.MediaElementMaker Cast(Org.WebRtc.IMediaElementMaker source);

            /// <summary>
            /// Creates an media element object from a media element type.
            /// </summary>
            static Org.WebRtc.IMediaElement Bind(Windows.UI.Xaml.Controls.MediaElement Element);

            /// <summary>
            /// Extracts a native media element from an media element object.
            /// </summary>
            static Windows.UI.Xaml.Controls.MediaElement Extract(Org.WebRtc.IMediaElement Element);
        };

    } // namespace WebRtc
} // namespace Org

