//import "windows.foundation.customattributes.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace Webrtc
    {


        [version(1.0)]
        [uuid(ff4fed17-f0aa-dd86-d1d8-33bbe7b97ea6)]
        [webhosthidden]
        interface IEventQueueMaker : IInspectable
        {
        };

        [webhosthidden]
        runtimeclass EventQueueMaker : [default] IEventQueueMaker
        {
            /// <summary>
            /// Cast from Org.Webrtc.IEventQueueMaker to Org.Webrtc.EventQueueMaker
            /// </summary>
            static Org.Webrtc.EventQueueMaker CastFromIEventQueueMaker(Org.Webrtc.IEventQueueMaker source);

            /// <summary>
            /// Creates an event queue object from a native queue type.
            /// </summary>
            static Org.Webrtc.IEventQueue BindQueue(Windows.UI.Core.CoreDispatcher Queue);

            /// <summary>
            /// Extracts a native queue from an event queue object.
            /// </summary>
            static Windows.UI.Core.CoreDispatcher ExtractQueue(Org.Webrtc.IEventQueue Queue);
        };

    } // namespace Webrtc
} // namespace Org

