//import "windows.foundation.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace Webrtc
    {


        /// <summary>
        /// A message queue for receiving delegate events.
        /// </summary>
        [version(1.0)]
        [uuid(98479893-fbbc-baf1-674b-020a498a996d)]
        interface IEventQueue : IInspectable
        {
        };

        /// <summary>
        /// A message queue for receiving delegate events.
        /// </summary>
        runtimeclass EventQueue : [default] IEventQueue
        {
            /// <summary>
            /// Cast from Org.Webrtc.IEventQueue to Org.Webrtc.EventQueue
            /// </summary>
            static Org.Webrtc.EventQueue CastFromIEventQueue(Org.Webrtc.IEventQueue source);

            /// <summary>
            /// The default windows message queue for the system GUI thread.
            /// </summary>
            static Org.Webrtc.IEventQueue GetDefaultForUi();

            /// <summary>
            /// Gets or sets the default system dispatcher object.
            /// </summary>
            static Org.Webrtc.IEventQueue Singleton { get; set; };
        };

    } // namespace Webrtc
} // namespace Org

