//import "windows.foundation.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        /// <summary>
        /// A message queue for receiving delegate events.
        /// </summary>
        [version(1.0)]
        [uuid(f9ad235b-42b0-0239-d7a3-6617a42ae227)]
        interface IEventQueue : IInspectable
        {
        };

        /// <summary>
        /// A message queue for receiving delegate events.
        /// </summary>
        runtimeclass EventQueue : [default] IEventQueue
        {
            /// <summary>
            /// Cast from Org.WebRtc.IEventQueue to Org.WebRtc.EventQueue
            /// </summary>
            [default_overload]
            [method_name("CastFromIEventQueue")]
            static Org.WebRtc.EventQueue Cast(Org.WebRtc.IEventQueue source);

            /// <summary>
            /// The default windows message queue for the system GUI thread.
            /// </summary>
            static Org.WebRtc.IEventQueue GetDefaultForUi();

            /// <summary>
            /// Gets or sets the default system dispatcher object.
            /// </summary>
            static Org.WebRtc.IEventQueue Singleton { get; set; };
        };

    } // namespace WebRtc
} // namespace Org

