//import "windows.foundation.customattributes.idl";
import "forwards.idl";
import "output.idl";

namespace Org
{
    namespace WebRtc
    {


        [version(1.0)]
        [uuid(ff4fed17-f0aa-dd86-d1d8-33bbe7b97ea6)]
        [webhosthidden]
        interface IEventQueueMaker : IInspectable
        {
        };

        [webhosthidden]
        runtimeclass EventQueueMaker : [default] IEventQueueMaker
        {
            /// <summary>
            /// Cast from Org.WebRtc.IEventQueueMaker to Org.WebRtc.EventQueueMaker
            /// </summary>
            static Org.WebRtc.EventQueueMaker CastFromIEventQueueMaker(Org.WebRtc.IEventQueueMaker source);

            /// <summary>
            /// Creates an event queue object from a native queue type.
            /// </summary>
            static Org.WebRtc.IEventQueue BindQueue(Windows.UI.Core.CoreDispatcher Queue);

            /// <summary>
            /// Extracts a native queue from an event queue object.
            /// </summary>
            static Windows.UI.Core.CoreDispatcher ExtractQueue(Org.WebRtc.IEventQueue Queue);
        };

    } // namespace WebRtc
} // namespace Org

