/*

 Copyright (c) 2017, Optical Tone Ltd.
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:

 1. Redistributions of source code must retain the above copyright notice, this
 list of conditions and the following disclaimer.
 2. Redistributions in binary form must reproduce the above copyright notice,
 this list of conditions and the following disclaimer in the documentation
 and/or other materials provided with the distribution.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
 ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

 The views and conclusions contained in the software and documentation are those
 of the authors and should not be interpreted as representing official policies,
 either expressed or implied, of the FreeBSD Project.
 
 */

namespace org
{
  namespace ortc
  {
    /// <summary>
    /// Controls the detailed settings of how the ORTC engine operates.
    /// </summary>
    [static]
    interface Settings
    {
      /// <summary>
      /// Apply all the default settings for how the ORTC engine should
      /// behave.
      /// </summary>
      [static]
      void applyDefaults();

      /// <summary>
      /// Apply a collection of json based settings.
      /// </summary>
      [static]
      bool apply(Json jsonSettings);

      /// <summary>
      /// Apply a specific string setting with a key and value.
      /// </summary>
      [static]
      void setString(string key, string value);

      /// <summary>
      /// Apply a specific integer setting with a key and value.
      /// </summary>
      [static]
      void setInt(string key, int64 value);

      /// <summary>
      /// Apply a specific unsigned integer setting with a key and value.
      /// </summary>
      [static]
      void setUInt(string key, uint64 value);

      /// <summary>
      /// Apply a specific boolean setting with a key and value.
      /// </summary>
      [static]
      void setBool(string key, bool value);

      /// <summary>
      /// Apply a specific floating point setting with a key and value.
      /// </summary>
      [static]
      void setFloat(string key, float value);

      /// <summary>
      /// Apply a specific double floating point setting with a key and value.
      /// </summary>
      [static]
      void setDouble(string key, double value);

      /// <summary>
      /// Clear a specific setting by its key.
      /// </summary>
      [static]
      void clear(string key);

      /// <summary>
      /// Clear all known settings.
      /// </summary>
      [static]
      void clearAll();
    };

  }
}
